/* content.js — GENERATED by build.py from content/*.json. Edit the JSON (or use /admin), not this file. */
(function (root) { root.Content = {
 "POPULAR": [
  [
   "pdf",
   "docx",
   "PDF to Word"
  ],
  [
   "docx",
   "pdf",
   "Word to PDF"
  ],
  [
   "jpg",
   "pdf",
   "JPG to PDF"
  ],
  [
   "pdf",
   "jpg",
   "PDF to JPG"
  ],
  [
   "heic",
   "jpg",
   "HEIC to JPG"
  ],
  [
   "png",
   "jpg",
   "PNG to JPG"
  ],
  [
   "jpg",
   "png",
   "JPG to PNG"
  ],
  [
   "webp",
   "png",
   "WebP to PNG"
  ],
  [
   "mov",
   "mp4",
   "MOV to MP4"
  ],
  [
   "mp4",
   "mp3",
   "MP4 to MP3"
  ],
  [
   "mp4",
   "gif",
   "MP4 to GIF"
  ],
  [
   "mp4",
   "webm",
   "MP4 to WebM"
  ],
  [
   "wav",
   "mp3",
   "WAV to MP3"
  ],
  [
   "m4a",
   "mp3",
   "M4A to MP3"
  ],
  [
   "mp3",
   "wav",
   "MP3 to WAV"
  ],
  [
   "ogg",
   "mp3",
   "OGG to MP3"
  ],
  [
   "csv",
   "xlsx",
   "CSV to Excel"
  ],
  [
   "xlsx",
   "csv",
   "Excel to CSV"
  ],
  [
   "json",
   "csv",
   "JSON to CSV"
  ],
  [
   "xlsx",
   "pdf",
   "Excel to PDF"
  ],
  [
   "md",
   "pdf",
   "Markdown to PDF"
  ],
  [
   "html",
   "pdf",
   "HTML to PDF"
  ],
  [
   "epub",
   "pdf",
   "EPUB to PDF"
  ],
  [
   "docx",
   "txt",
   "Word to text"
  ],
  [
   "svg",
   "png",
   "SVG to PNG"
  ],
  [
   "png",
   "ico",
   "PNG to ICO"
  ],
  [
   "png",
   "webp",
   "PNG to WebP"
  ],
  [
   "tiff",
   "jpg",
   "TIFF to JPG"
  ],
  [
   "obj",
   "glb",
   "OBJ to GLB"
  ],
  [
   "stl",
   "glb",
   "STL to GLB"
  ],
  [
   "glb",
   "stl",
   "GLB to STL"
  ],
  [
   "ttf",
   "woff",
   "TTF to WOFF"
  ]
 ],
 "STEPS": [
  [
   "Choose a file",
   "Drop it on the page or browse for it. Images, documents, spreadsheets, audio, video, archives, fonts and 3D models are all accepted."
  ],
  [
   "Pick the format",
   "The To list only ever shows formats that will genuinely work for your file, so there is nothing to guess."
  ],
  [
   "Download",
   "The result appears in a moment with a Download button, and a copy is kept in Your files in case you need it again."
  ]
 ],
 "FAQ": [
  [
   "Is Convert Files free?",
   "Yes, completely. There is no premium tier, no daily limit, no watermark and no account. It is free for anyone to use."
  ],
  [
   "Do I need to sign up?",
   "No. There is no sign-in or sign-up anywhere on the site. Open the page, drop a file, download the result."
  ],
  [
   "Are my files uploaded anywhere?",
   "No. Every conversion runs inside your own browser using your computer’s processor. The file never leaves your device, which is also why there is nothing to delete afterwards — nothing was ever sent."
  ],
  [
   "Why does the first conversion of a new type take a moment?",
   "The converter for that family (PDF, spreadsheets, HEIC, AAC and so on) is fetched the first time it is needed and then cached by your browser. Later conversions of the same kind start instantly."
  ],
  [
   "What is the file size limit?",
   "It depends on the type, because everything has to fit in the browser’s memory: images 80 MB, documents 60 MB, spreadsheets 60 MB, audio 250 MB, 3D models 250 MB, video 600 MB and archives 800 MB. Video re-encoding is limited to 15 minutes of footage."
  ],
  [
   "Where do converted files go?",
   "To your Downloads folder when you press Download, and to the Your files tab, which keeps a copy in this browser’s storage so you can download it again later. Clear all removes them."
  ],
  [
   "Why is a format missing from the To list?",
   "Because that particular pair would not produce a meaningful result, or because your browser cannot encode it. A video cannot honestly become a Word document, and Chrome cannot write AVIF without extra help. The Formats tab shows exactly what your browser can do."
  ],
  [
   "Does it work offline?",
   "Once the converters you use have been cached, yes for those types. The first use of each converter needs an internet connection."
  ],
  [
   "Which browser works best?",
   "A current Chrome or Edge has the widest support, including video re-encoding and HEIC. Safari and Firefox handle images, documents, spreadsheets, audio and 3D; they lack some of the video encoders."
  ]
 ],
 "ABOUT": {
  "intro": [
   "Convert Files is a free file converter that runs entirely in your browser. There is no server doing the work, no upload, no queue and no account — the page you are looking at is the whole product.",
   "Most online converters send your file to a machine you will never see, convert it there and keep a copy for a while. This one does the opposite: it brings the converter to you. Images are decoded and re-encoded by your browser’s own engines, documents are rebuilt from their structure, audio and video are re-encoded with the codecs already inside Chrome, and every result is written straight to your disk.",
   "That design is the reason it can be free and public. Nothing is stored, nothing is metered, and there is no cost that has to be recovered from you."
  ],
  "points": [
   "Free, with no limits on how many files you convert",
   "No sign-in, sign-up, email or payment details — ever",
   "Your file never leaves your device",
   "Works on Mac, Windows, Linux, iPad and Android in a modern browser",
   "Honest about what it cannot do: every pair offered is one that actually works"
  ]
 },
 "GUIDES": [
  {
   "slug": "heic-to-jpg",
   "cat": "image",
   "fam": "image",
   "title": "HEIC to JPG: why iPhone photos will not open on Windows and Android",
   "teaser": "Since iOS 11 the iPhone saves photos as HEIC. Here is why other devices choke on them, and how to fix it in one step.",
   "body": [
    "p:Every photo an iPhone has taken since 2017 is stored as HEIC unless you changed a setting. It is a good format — roughly half the size of a JPG at the same quality — but it is licensed, so Windows, Android and every browser except Safari refuse to open it. You share a photo, the other person sees a broken icon.",
    "h:The one-step fix",
    "p:Convert the HEIC to JPG. JPG opens on everything made in the last twenty-five years. Drop the file on Convert Files, leave the target on <code>.jpg</code> (it is the default for HEIC), press Convert. The first time in Chrome a small decoder is fetched; after that it is instant.",
    "p:For a photo you plan to edit further, choose <code>.png</code> instead: it is lossless, so nothing is thrown away before your edits. For a photo going into a document, choose <code>.docx</code> and you get a Word file with the picture already placed.",
    "h:Stopping it at the source",
    "p:If you would rather the phone never made HEIC files at all: Settings › Camera › Formats › Most Compatible. Photos will take about twice the space, which is the trade-off.",
    "h:What about quality?",
    "p:HEIC to JPG is lossy to lossy, so keep the quality slider at 90% or above. At that setting the difference is invisible; the file is simply a bit larger than the HEIC was.",
    "h:Why Apple moved to HEIC in the first place",
    "p:HEIC is a HEIF container holding images coded with HEVC, the same compression used for 4K video. Roughly speaking it stores the same photograph at half the size of a JPG at the same visible quality, which on a 128&nbsp;GB phone is thousands of extra pictures. It also does things JPG simply cannot: 10&nbsp;bits per colour channel instead of 8, so skies and skin tones step more smoothly; an alpha channel; a depth map from Portrait mode; and several images in one file, which is how burst shots and Live Photos are stored.",
    "p:None of that is the problem. The problem is that a format being better is not the same as a format being <em>openable</em>.",
    "h:Why Windows and Android choke on them",
    "p:HEVC is patent-encumbered. The licensing is split across more than one patent pool, and the practical result is that companies who would have to pay for a decoder mostly do not ship one. Windows 10 and 11 can display HEIC only if the HEVC Video Extensions are installed from the Microsoft Store, which is a paid add-on for most people. Android has supported HEIF in the framework since version 9, but individual apps and older handsets often still refuse. Chrome, Firefox and Edge do not decode HEIC at all &mdash; Safari is the exception, because Apple ships the decoder.",
    "p:So the file is fine. The photo inside it is fine. Everything that would open it is what is missing, and you usually cannot install your way out of that on someone else's computer.",
    "h:What you lose in the conversion, honestly",
    "p:A JPG is one 8-bit image and nothing else, so anything HEIC was carrying alongside the picture does not survive. In practice that means the depth map behind Portrait mode blur, the HDR gain map some newer iPhones write, and the extra colour precision of 10-bit. For an ordinary photograph you will not see the difference. For a picture you intend to grade or push hard in an editor, it is a real loss &mdash; convert to PNG instead, which is lossless, and keep the HEIC original.",
    "p:Live Photos are worth a note of their own. The moving part is not inside the HEIC; it is a separate MOV file that the phone keeps paired with it. Converting the still image does not, and cannot, take the motion with it. If you want the movement, export the video separately.",
    "h:Converting a whole camera roll",
    "p:Select as many HEIC files as you like in one go &mdash; the converter works through them one after another and offers a zip of the results at the end. There is no per-file wait and no queue, because nothing is being uploaded to wait behind anyone else's job. A few hundred photos on a normal laptop takes a couple of minutes.",
    "h:HEIC, HEIF, HEVC: which is which",
    "p:HEIF is the container format. HEVC (also called H.265) is the compression used for the picture inside it. HEIC is the name Apple uses for the combination, and it is the extension you see on the phone. When Windows asks you to install “HEVC Video Extensions” to open a photo, this is why &mdash; it needs the video decoder to read the still image."
   ],
   "tryFrom": "heic",
   "tryTo": "jpg",
   "seo_title": "HEIC to JPG: why iPhone photos will not open"
  },
  {
   "slug": "pdf-to-word",
   "cat": "documents",
   "fam": "doc",
   "title": "PDF to Word, honestly: what survives the trip and what does not",
   "teaser": "A PDF is a picture of a page; a Word file is a description of one. That difference explains every conversion quirk.",
   "body": [
    "p:A PDF records where each letter sits on the page. A Word document records paragraphs, headings and lists and lets Word decide where they land. Converting between them means guessing the structure back from the positions, which is why no PDF-to-Word converter is perfect — including this one.",
    "h:What comes across well",
    "p:Running text, paragraph breaks, and page breaks. Convert Files reads the text layer of each page, groups lines into paragraphs by spacing and punctuation, and writes a clean Word file you can edit immediately.",
    "h:What does not",
    "p:Images, columns, tables and exact fonts. A PDF made from a scan has no text layer at all, so nothing can be extracted; you would need OCR first. Two-column layouts may come out interleaved.",
    "h:The other direction is much better",
    "p:Word to PDF keeps everything — headings, bold and italic, lists, quotes, tables and pictures — because it goes from structure to layout, which is the easy way round. If you have the original Word file, always convert from that.",
    "p:Tip: if you only need the words, choose <code>.txt</code> or <code>.md</code> as the target. It is faster and there is no layout to get wrong.",
    "h:Why the layout moves when you convert",
    "p:A Word document says “here is a heading, then a paragraph, then a table” and lets the program decide where the words land. A PDF says “put the glyph A at 72.4 points from the left and 690.1 points from the bottom in 11pt Helvetica” and says it again for every character on the page. There is no paragraph in a PDF, only characters that happen to sit next to each other.",
    "p:Converting means reading those positions and inferring the structure back: characters close together are a word, words on a line are a line, lines with matching spacing and indentation are a paragraph, a run of larger bold text is probably a heading. Most of the time this is right. Where it goes wrong is exactly where you would expect &mdash; multi-column layouts, text flowing around an image, tables drawn as lines rather than marked up as tables, and headers and footers that reappear mid-document.",
    "h:If your PDF is a scan, there is nothing to convert",
    "p:This is the single most common disappointment. A PDF produced by a scanner or a phone camera contains a photograph of a page. There is no text in it at all &mdash; not hidden, not compressed, not locked. Converting it gives you a document with a picture in it, because that is genuinely all there was.",
    "p:Getting text out of a scan requires OCR, which recognises letter shapes in an image and guesses the words. Convert Files does not do OCR; it converts what is in the file rather than inventing what might have been. A quick way to tell which kind of PDF you have: open it and try to select a sentence with the mouse. If the selection highlights individual words, there is real text. If you get a blue box over the whole page, it is a scan.",
    "h:What survives and what does not",
    "p:Carried across: headings, paragraphs, bold and italic, bulleted and numbered lists, block quotes, hyperlinks, embedded images, and tables where the PDF marked them as tables. Not carried across: exact page geometry, fonts that were not embedded, multi-column flow, footnote positioning, form fields, annotations and comments, and anything drawn as a vector diagram rather than written as text.",
    "p:A useful way to think about it: you are getting the content back so you can edit it, not getting a pixel-perfect replica you can print. If you need the replica, keep the PDF.",
    "h:Sometimes a different target is the better answer",
    "p:If all you want is the words &mdash; to paste into an email, search, or feed to something else &mdash; converting to TXT is faster and cannot go wrong in the ways DOCX can. If you want the structure but not Word, Markdown keeps headings, lists and emphasis as plain text that stays readable in any editor for ever. If you want to put it on a website, HTML preserves the most structure of the three.",
    "h:Getting a cleaner result",
    "p:PDFs exported from Word, Google Docs or a web page convert far better than PDFs exported from InDesign, LaTeX or a design tool, because the first group started life with the structure the converter is trying to rebuild. If you have any choice about where the PDF comes from, that is the choice that matters most. Failing that, expect to spend a few minutes fixing headings and table borders &mdash; which is still considerably less time than retyping it."
   ],
   "tryFrom": "pdf",
   "tryTo": "docx",
   "seo_title": "PDF to Word: what survives the trip"
  },
  {
   "slug": "which-image-format",
   "cat": "image",
   "fam": "image",
   "title": "JPG, PNG, WebP or AVIF — which image format should you use?",
   "teaser": "Four formats cover almost every job. Pick by what the picture is and where it is going, not by habit.",
   "body": [
    "p:There are dozens of image formats, and four of them cover almost every real job.",
    "h:JPG — photographs going anywhere",
    "p:Small, universal, lossy. Right for photos sent by email or message, uploaded to a shop, or printed. Wrong for screenshots, logos and anything with sharp text, where the compression leaves smudges. Keep quality at 85–92%.",
    "h:PNG — screenshots, logos, transparency",
    "p:Lossless and supports transparent backgrounds. Files are bigger than JPG for photos, but perfect for anything with flat colour, text or a cut-out background.",
    "h:WebP — the web, when you control the site",
    "p:About 30% smaller than JPG at the same quality, supports transparency, and every current browser opens it. Wrong for sending to people: many desktop apps still cannot open a WebP, which is why “WebP to PNG” is one of the most common conversions there is.",
    "h:AVIF — smallest of all, least compatible",
    "p:Roughly half the size of JPG. Browsers display it, but most other software does not yet. Use it for websites you build; convert it to JPG or PNG for anything else.",
    "h:A quick rule",
    "ul:Photo to a person → JPG|Screenshot, logo or transparent image → PNG|Image on a website you run → WebP (or AVIF)|Anything you received that will not open → PNG",
    "h:JPG: the safe default for photographs",
    "p:Lossy, 8 bits per channel, no transparency, and understood by literally everything. It compresses photographs well because its maths assumes smooth gradients and gentle detail, which is what photographs are made of. It handles hard edges badly, which is why text and screenshots saved as JPG look fuzzy and develop grey smudges around the letters. Every save is another generation of loss, so edit from an original and export to JPG once, at the end.",
    "h:PNG: lossless, and the one with real transparency",
    "p:Every pixel comes back exactly as it went in, and the alpha channel gives you genuine partial transparency rather than one colour knocked out. That makes it right for logos, icons, diagrams, screenshots, anything with text in it, and any image you are going to keep editing. The cost is size: a photograph as PNG is routinely five to ten times larger than the same photograph as JPG, for a difference nobody can see.",
    "h:WebP: smaller than both, and safe on the web now",
    "p:WebP does lossy and lossless in one format, supports transparency in both modes, and typically lands 25&ndash;35% below the equivalent JPG or PNG. Every current browser supports it. The catch is outside the browser: plenty of desktop software, older phones, print workflows and upload forms still reject it, so it is a great format to <em>serve</em> and a poor format to <em>send someone</em>.",
    "h:AVIF: the smallest, with the newest support",
    "p:AVIF uses the still-image side of the AV1 video codec. It beats WebP again on size, often substantially, and adds 10- and 12-bit colour, HDR and good transparency. Browser support is broad now. Support in ordinary applications is patchier than WebP's, and encoding is slower. Use it for images on a site you control, where the saving is worth it and a fallback is easy.",
    "h:What about transparency?",
    "p:PNG, WebP and AVIF all have a real alpha channel. JPG has none at all, so anything transparent has to be flattened onto a solid colour when you convert &mdash; white, unless you pick another. GIF has one-bit transparency, meaning a pixel is either fully there or fully gone, which is why GIF logos so often have a ragged fringe.",
    "h:What about animation?",
    "p:GIF animates and is accepted everywhere, but it is limited to 256 colours per frame and the files are enormous. WebP and AVIF both animate at a fraction of the size with full colour. For anything longer than a couple of seconds, an actual video &mdash; MP4 or WebM &mdash; is smaller again by an order of magnitude and is what most sites quietly use behind what looks like a GIF.",
    "h:A short decision list",
    "p:A photograph for someone else, or for anything you do not control: JPG. A logo, icon, screenshot, or anything with text or transparency: PNG. Images on a website you run: WebP, or AVIF if you can. An original you will keep editing: PNG, or the camera's own raw file. A short loop: WebP if the destination allows it, GIF if it must work everywhere, MP4 if it is longer than a moment."
   ],
   "tryFrom": "webp",
   "tryTo": "png",
   "seo_title": "JPG, PNG, WebP or AVIF: which to use"
  },
  {
   "slug": "mov-to-mp4",
   "cat": "video",
   "fam": "video",
   "title": "MOV to MP4: making iPhone and Mac videos play everywhere",
   "teaser": "QuickTime MOV and MP4 are near-identical containers, so why does one play everywhere and the other not?",
   "body": [
    "p:A MOV file and an MP4 file are almost the same thing: both are boxes of the same shape holding video and audio streams. The difference is what is inside. iPhones and Macs often put HEVC (H.265) video into a MOV, and HEVC is what Windows, Android and most web players refuse.",
    "h:What the conversion does",
    "p:Convert Files re-encodes the video to H.264 and the audio to AAC, then writes an MP4. That pair plays on essentially every device, TV, browser and messaging app. It is a real re-encode: every frame is decoded and encoded again inside your browser, so a two-minute clip takes a minute or two and the tab has to stay open.",
    "h:Settings that matter",
    "ul:Width — leave at 0 to keep the size, or set 1280 for a much smaller file that still looks good on a phone|Frames per second — 30 is right for almost everything; 60 doubles the work for sports and games footage|Quality — 85% is the sweet spot; lower if the file must be tiny",
    "h:WebM instead?",
    "p:If the video is going onto a website you build, <code>.webm</code> (VP9 + Opus) is usually smaller than MP4 at the same quality and is supported by all modern browsers. For anything else, MP4.",
    "p:Only the audio? Choose <code>.mp3</code> or <code>.m4a</code> as the target and the video track is dropped entirely.",
    "h:Container and codec are not the same thing",
    "p:This is the whole confusion in one sentence: MOV and MP4 are boxes, and H.264, HEVC and AV1 are what goes in them. MP4 was standardised <em>from</em> Apple's QuickTime file format, so the two boxes are nearly the same shape internally. A .mov and a .mp4 from the same iPhone very often contain a byte-identical video stream, differing mainly in the label on the outside.",
    "p:Which is why the failure is so infuriating. The player can decode the video perfectly well. It just does not like the box.",
    "h:So why does the MOV refuse to play?",
    "p:Usually one of three reasons. The program checks the extension and declines before it even opens the file &mdash; common in upload forms and older editors. Or the container holds QuickTime-specific structures, such as timecode or closed-caption tracks, that the player does not expect and gives up on. Or, most often on recent iPhones, the video inside is HEVC rather than H.264, and the player has no HEVC decoder &mdash; the same patent-licensing story that makes HEIC photos hard to open.",
    "h:H.264 is the one that plays everywhere",
    "p:If a video has to work on an unknown device, MP4 with H.264 video and AAC audio is the combination with the widest support of anything in existence: phones, TVs, browsers, editors, projectors, ten-year-old laptops. HEVC and AV1 are both more efficient &mdash; meaningfully smaller at the same quality &mdash; but each is a gamble on the far end having a decoder. Efficiency is worth a lot on a website you control and nothing at all in an email attachment.",
    "h:What actually happens when you convert",
    "p:Every frame is decoded and re-encoded, in your browser, using your machine's processor. That is why a long clip takes real time, roughly comparable to the length of the video for high-definition footage, and why the tab needs to stay open and in the foreground while it works. It also means this is a lossy step: you are re-compressing already-compressed video, so work from the highest quality source you have rather than from something already converted twice.",
    "h:Making the file smaller while you are at it",
    "p:Resolution is the biggest lever by a wide margin. Setting the width to 1280 takes a 4K clip to roughly a sixteenth of the pixel count, and on a phone screen the result is indistinguishable. Frame rate is the second: 60fps footage of someone talking looks exactly the same at 30. Bitrate is the fiddly one &mdash; adjust the first two before reaching for it.",
    "h:A note on audio",
    "p:MP4 expects AAC. If your MOV carries uncompressed PCM audio &mdash; common from screen recordings and some cameras &mdash; the sound is re-encoded to AAC as part of the conversion, which is normal and is where a surprising amount of the file size saving comes from."
   ],
   "tryFrom": "mov",
   "tryTo": "mp4",
   "seo_title": "MOV to MP4: play iPhone video anywhere"
  },
  {
   "slug": "3d-model-to-glb",
   "cat": "3d & ar",
   "fam": "model3d",
   "title": "Getting a 3D model into AR: OBJ and STL to GLB",
   "teaser": "Android Scene Viewer, web AR and most engines want glTF. Here is how the older formats map onto it.",
   "body": [
    "p:If you have a model from a CAD tool or a 3D printer workflow, it is probably an OBJ or an STL. Augmented-reality viewers — Android’s Scene Viewer, model-viewer on the web, Unity and three.js pipelines — want glTF, and specifically its single-file binary form, GLB.",
    "h:What GLB is",
    "p:glTF is a JSON description of a scene (meshes, materials, nodes) plus a binary buffer of vertex data. GLB packs both into one file so nothing can go missing. It is small, loads fast and is the format the AR ecosystem has standardised on.",
    "h:What converts, and what does not",
    "p:Convert Files carries the geometry: every vertex and triangle, with node transforms applied so the model sits where it should. It does not carry materials, textures or animations — an OBJ’s <code>.mtl</code> file and its texture images are not read. The result is a clean grey mesh, which is exactly what you want as a starting point for assigning your own material in a viewer or engine.",
    "h:Units and scale",
    "p:glTF is in metres. STL files are unitless and often exported in millimetres, so a 20 mm ring becomes a 20 m ring in AR. Check the scale in your viewer; most let you set it in one field. Convert Files does not rescale, because it cannot know which unit the source used.",
    "h:Going the other way",
    "p:GLB to STL is useful for printing a model that only exists as a glTF. Node transforms are baked in, so the printed part comes out at the pose you see in the viewer.",
    "h:What each format actually carries",
    "p:STL is the simplest: an unordered pile of triangles, with no colour, no texture, no material, no units and no scene structure. It exists because 3D printers need a watertight shape and nothing else. OBJ adds names, groups, texture coordinates and a reference to a separate .mtl file for materials, which in turn references image files &mdash; three files that must travel together and frequently do not. PLY comes out of 3D scanners and photogrammetry and usually carries per-vertex colour, which is a different thing from a texture.",
    "p:glTF was designed for the opposite problem: shipping a finished scene to a viewer. It carries meshes, a node hierarchy, physically-based materials, textures, skins and animation, in JSON with binary buffers alongside. GLB is that same scene packed into one binary file, so there is nothing to lose in transit. This is why it has become the format AR asks for.",
    "h:What AR viewers want",
    "p:Android's Scene Viewer takes glTF and GLB. The web, via the model-viewer element and essentially every WebGL engine, takes GLB. Apple's Quick Look on iOS is the exception &mdash; it wants USDZ, a different lineage entirely, so an iOS-native AR experience needs that conversion separately. If you are publishing one file for the widest reach, GLB is the answer, with USDZ added for iOS if you need it.",
    "h:Scale is where models go wrong",
    "p:glTF defines its units as metres, Y-up, right-handed. STL has no unit convention at all, and the 3D printing world has simply agreed to treat the numbers as millimetres. The arithmetic follows: a model authored for printing usually arrives in an AR viewer a thousand times too large, and the first thing you see is the inside of a triangle. If your converted model appears vast, or vanishes entirely, scale is almost always why &mdash; not the conversion.",
    "h:Materials, textures and what gets dropped",
    "p:Converting up the chain adds nothing that was not there. An STL has no colour, so its GLB has no colour; you get clean geometry with a default material, which is the correct result rather than a failure. An OBJ's materials live in a .mtl file that is not read here, so geometry converts and materials do not. A PLY's per-vertex colours are kept where the target supports them.",
    "p:Going the other way &mdash; GLB or glTF down to STL &mdash; deliberately throws away everything except the shape, which is exactly what a slicer wants.",
    "h:Before you send it to a printer",
    "p:Geometry that looks right in a viewer is not automatically printable. Slicers want a closed, manifold surface: no holes, no faces pointing the wrong way, no edges shared by three triangles. A model built for display often fails all three, because none of it matters when you are only ever looking at the outside. Convert first, then check in the slicer, and repair there rather than blaming the conversion."
   ],
   "tryFrom": "obj",
   "tryTo": "glb",
   "seo_title": "OBJ and STL to GLB for AR"
  },
  {
   "slug": "is-it-safe",
   "cat": "privacy",
   "fam": "archive",
   "title": "Is it safe to convert files online? What “nothing is uploaded” means here",
   "teaser": "Most converters upload your file to a server. This one never does. Here is how you can check that yourself.",
   "body": [
    "p:When you use a typical online converter, your file travels to a server, sits there while it is converted, and often stays for hours or days afterwards. For a holiday photo that is a minor annoyance. For a contract, a medical record or a client’s design it is a real problem.",
    "h:How Convert Files is different",
    "p:There is no server-side conversion at all. The page downloads a converter into your browser — a PDF renderer, an image encoder, an audio codec — and runs it on your computer. The file is read from your disk into the browser’s memory and the result is written back to your disk. That is the entire path.",
    "h:How to verify it",
    "p:Open your browser’s developer tools (F12), go to the Network tab, and convert something. You will see the converter libraries being fetched the first time, and nothing else: no upload, no request carrying your file. Or go further and disconnect from the internet after the first conversion of each type; it keeps working.",
    "h:What is stored",
    "p:Only what you can see in the Your files tab, which lives in your own browser’s storage on your own device. Clear all removes it. Nothing about you or your files is sent to us, because there is no “us” receiving anything.",
    "h:How to check for yourself, in about thirty seconds",
    "p:Do not take anyone's word for this, including ours. Open your browser's developer tools before you convert &mdash; F12 on Windows, or Cmd&#8209;Option&#8209;I on a Mac &mdash; and select the Network tab. Then convert a file and watch. You will see the page's own scripts load, and you will see nothing carrying your file out. No upload request, no POST with a body the size of your document, nothing. The conversion happens between the file picker and the download, and never crosses the network.",
    "p:There is a second test. Load the page, then switch off your wi-fi, then convert an image. It still works, because everything needed is already in the browser. This holds for conversions the page can do on its own; a few formats fetch a decoder library the first time you use them, and those need the network for that one download rather than for your file.",
    "h:What “in the browser” actually means",
    "p:Modern browsers can do genuinely serious work. Canvas decodes and re-encodes images. WebCodecs gives access to the same video and audio encoders the browser uses for video calls. WebAssembly runs compiled C libraries at close to native speed. CompressionStream does gzip. None of this needs a server &mdash; servers were doing it only because browsers could not, and that stopped being true some years ago.",
    "p:The practical consequence is that your file is read from disk into memory, transformed in memory, and written back to disk. The page has no way to send it anywhere without making a network request, and you can watch for that request yourself.",
    "h:What is collected, precisely",
    "p:Two things, both counts. That a page was viewed, and that a conversion from one format to another finished or failed. No file names, no file contents, no file sizes, no identifiers that follow you between visits. The numbers on the home page are the total of those counts. If your browser sends Do Not Track or Global Privacy Control, even the counts are skipped.",
    "h:What to look for on other converters",
    "p:Most online converters do upload. That is not automatically sinister &mdash; it is how the technology worked for twenty years &mdash; but it changes the question from “do I trust this page” to “do I trust this company, its hosting, its staff, its retention policy and whoever eventually buys it”. Read the privacy policy for a retention period. Look for a stated deletion window. Be more careful the more the document matters: a holiday photo and a signed contract deserve different levels of suspicion.",
    "p:The Network tab test works on any site, not just this one. If you are curious whether a converter uploads, spend the thirty seconds.",
    "h:Where a server genuinely is required",
    "p:Honesty demands the limits. Some conversions are impractical in a browser today: very large video files that exceed available memory, formats whose only implementation is a large native application, and anything needing OCR or a licensed codec. Where that is the case here, the conversion is simply not offered, rather than quietly shipped somewhere else. A pair that is missing is a pair that does not work &mdash; not a pair that works differently."
   ],
   "tryFrom": "pdf",
   "tryTo": "png",
   "seo_title": "Is it safe to convert files online?"
  },
  {
   "slug": "csv-vs-excel",
   "cat": "spreadsheets",
   "fam": "table",
   "title": "CSV vs Excel: when to convert, and the three things that go wrong",
   "teaser": "CSV is the universal spreadsheet language and Excel is the universal spreadsheet app. Moving between them is easy — with three traps.",
   "body": [
    "p:CSV is just text: one row per line, cells separated by commas. Every system exports it and every system imports it. XLSX is Microsoft’s format: multiple sheets, formatting, formulas, dates that know they are dates. Converting between them is a daily task, and three things regularly go wrong.",
    "h:1. Leading zeros disappear",
    "p:A postcode like 02139 or a product code like 000451 becomes 2139 and 451 when Excel decides the column is numeric. If the codes matter, keep them as text before converting, or fix the column type after.",
    "h:2. Dates change shape",
    "p:CSV has no idea what a date is; it is just characters. 03/04/2026 is 3 April in most of the world and 4 March in the US. Convert Files keeps the text exactly as it was, so what you see is what was written — but check the convention before you trust a column.",
    "h:3. Only the first sheet is exported",
    "p:CSV can hold one table. Converting a workbook with five sheets to CSV gives you the first one. If you need all of them, convert to <code>.pdf</code> or <code>.docx</code> instead, which puts every sheet in as its own table.",
    "h:Beyond Excel",
    "p:The same data also converts to JSON for developers, to SQL insert statements for a database, to Markdown for documentation, and to ODS for LibreOffice.",
    "h:The leading zero problem",
    "p:Open a CSV of postcodes, product codes, or phone numbers in Excel and watch the zeros disappear. 01234 becomes 1234, because the column looked numeric and Excel helpfully made it a number. The data in the file was never wrong; the interpretation on opening was. And if you then save, the corrected version is written back over the original.",
    "p:The fix is to import rather than open &mdash; Data &rsaquo; From Text/CSV &mdash; and set the column type to Text before the data lands. Converting the CSV to XLSX first has the same effect, because the cell types are then recorded in the file instead of guessed at open time.",
    "h:The date problem, which is worse",
    "p:Excel converts anything date-shaped into a date. A part number like 3-10 becomes 3 October. A ratio written 1/2 becomes a date in January. The famous case is genetics: gene names such as SEPT2 and MARCH1 were being silently turned into dates so persistently that in 2020 the naming committee renamed the genes rather than keep fighting the spreadsheet.",
    "p:This one is genuinely destructive, because the original text is gone once it has become a date serial number. There is no undo after saving. Import as Text, every time, for any column that is an identifier rather than a quantity.",
    "h:The encoding problem",
    "p:A CSV is text, and text needs an encoding. Write one in UTF-8 &mdash; which anything modern does &mdash; and open it in Excel without a byte order mark, and accented characters, currency symbols and anything non-English arrive as mojibake: é as Ã©, and so on. The file is correct. Excel simply guessed the wrong encoding. Either save with a BOM or use the import dialogue and choose UTF-8 explicitly.",
    "h:Delimiters are not always commas",
    "p:In locales where the comma is the decimal separator &mdash; most of Europe &mdash; Excel writes and expects semicolons in its CSVs. A file exported in Germany and opened in the United States lands entirely in column A, and vice versa. It is not corrupt, it is punctuated for a different audience. This is also the strongest argument for TSV: a tab almost never appears inside a real value, so nothing has to be quoted or escaped and the ambiguity disappears.",
    "h:What a CSV cannot hold at all",
    "p:Formulas, formatting, colours, column widths, charts, pivot tables, comments, frozen panes, more than one sheet, and cell types. Converting XLSX to CSV keeps the values you can see and drops every one of those, permanently. That is not a flaw &mdash; it is the entire point of the format &mdash; but it is worth knowing before it is your only copy.",
    "h:So when do you use which?",
    "p:Use CSV to move data between systems: imports, exports, databases, scripts, anything where another program is the reader. Use XLSX when a person is the reader, or when formulas, multiple sheets or formatting carry meaning. Use TSV when the data itself is full of commas and quoting keeps going wrong. And keep the spreadsheet as the master copy, exporting CSV when something needs it, rather than the other way round."
   ],
   "tryFrom": "csv",
   "tryTo": "xlsx",
   "seo_title": "CSV vs Excel: when to convert"
  },
  {
   "slug": "photo-ka-size-kam-kaise-kare",
   "lang": "hi",
   "cat": "इमेज",
   "fam": "image",
   "title": "फोटो का साइज़ कम कैसे करें — 20 KB, 50 KB या 100 KB में",
   "seo_title": "फोटो का साइज़ कम कैसे करें (KB में)",
   "teaser": "फॉर्म कहता है “फोटो 50 KB से कम होनी चाहिए” और आपकी फोटो 4 MB की है। बिना कोई ऐप डाउनलोड किए, मोबाइल से ही, एक मिनट में यह कैसे करें।",
   "alt": null,
   "tryTool": "compress-image",
   "tryLabel": "फोटो का साइज़ अभी कम करें",
   "body": [
    "p:लगभग हर ऑनलाइन फॉर्म — SSC, UPSC, रेलवे, बैंक, कॉलेज एडमिशन, पासपोर्ट, PAN — फोटो और सिग्नेचर के लिए एक साइज़ लिमिट रखता है: “JPG, 20 से 50 KB के बीच”, “सिग्नेचर 10–20 KB”। और आज के फोन की एक फोटो 3–6 MB की होती है, यानी लिमिट से सौ गुना बड़ी। फॉर्म अपलोड ही नहीं होता।",
    "h:KB और MB में फर्क समझ लें",
    "p:1 MB = 1024 KB। मतलब 4 MB की फोटो 4096 KB की है, और उसे 50 KB में लाना है — यानी अस्सी गुना छोटा। यह डरावना लगता है, लेकिन असल में आसान है, क्योंकि फोटो का साइज़ दो चीज़ों से तय होता है: उसकी लंबाई-चौड़ाई (पिक्सेल) और उसकी JPEG क्वालिटी। दोनों को थोड़ा-थोड़ा घटाने से साइज़ बहुत तेज़ी से गिरता है।",
    "h:सबसे आसान तरीका: साइज़ लिखो, फोटो डालो",
    "p:Convert Files के <a href=\"/compress-image/\">Compress Image</a> टूल में बस वह नंबर लिखिए जो फॉर्म मांग रहा है — 20, 50, 100 — और फोटो डाल दीजिए। टूल खुद सबसे अच्छी क्वालिटी ढूंढता है जो उस लिमिट में आ जाए, और ज़रूरत पड़े तभी फोटो को थोड़ा छोटा करता है। न कोई ऐप, न साइन-अप, न वॉटरमार्क।",
    "p:सबसे ज़रूरी बात: आपकी फोटो कहीं अपलोड नहीं होती। पूरा काम आपके फोन या कंप्यूटर के ब्राउज़र के अंदर होता है। फॉर्म की फोटो, आधार, सिग्नेचर — ये निजी चीज़ें हैं, और इन्हें किसी अनजान वेबसाइट के सर्वर पर भेजने की कोई ज़रूरत नहीं है।",
    "h:एग्ज़ाम फॉर्म के लिए तैयार प्रीसेट",
    "p:टूल में “Exam photo 3.5×4.5 cm · ≤50 KB” और “Exam signature 4×2 cm · ≤20 KB” जैसे प्रीसेट हैं। इन्हें दबाते ही साइज़ और लंबाई-चौड़ाई दोनों सेट हो जाती हैं। फिर भी अपने फॉर्म का नोटिफिकेशन एक बार ज़रूर पढ़ लें — हर फॉर्म की अपनी लिमिट होती है, और कुछ फॉर्म पिक्सेल में साइज़ मांगते हैं (जैसे 200×230 px)।",
    "h:मोबाइल से कैसे करें",
    "p:फोन के Chrome या Safari में यही पेज खोलिए, “Choose files” पर टैप करके गैलरी से फोटो चुनिए, साइज़ लिखिए, Compress दबाइए और Download कर लीजिए। फाइल Downloads फोल्डर में आ जाती है, जहाँ से फॉर्म में अपलोड कर सकते हैं। कंप्यूटर की ज़रूरत नहीं।",
    "h:क्वालिटी खराब तो नहीं होगी?",
    "p:50 KB में चेहरे की फोटो बिल्कुल साफ रहती है — इतने में लगभग 600 पिक्सेल चौड़ी शार्प तस्वीर आ जाती है, जो फॉर्म के छोटे बॉक्स के लिए ज़्यादा ही है। 20 KB में फोटो छोटी हो जाती है, लेकिन 20 KB मांगने वाले फॉर्म वैसे भी छोटी फोटो (या सिग्नेचर) ही चाहते हैं। 100 KB और उससे ऊपर में फर्क आँख से दिखता ही नहीं।",
    "h:PNG फोटो का साइज़ कम क्यों नहीं होता?",
    "p:PNG “लॉसलेस” फॉर्मैट है — वह क्वालिटी घटाकर साइज़ नहीं बचा सकता, सिर्फ पिक्सेल घटाकर। इसलिए अगर फॉर्म JPG मांगता है (ज़्यादातर मांगते हैं), तो आउटपुट को Auto या JPG पर ही रहने दें; टूल PNG को JPG बना देगा और साइज़ कई गुना कम हो जाएगा।",
    "h:एक बार में कई फोटो",
    "p:फोटो और सिग्नेचर दोनों एक साथ चुन सकते हैं, या पूरे परिवार के फॉर्म की फोटो एक बार में। हर फोटो अलग-अलग डाउनलोड होती है, या सब एक zip में।",
    "h:अगर फोटो अभी भी अपलोड न हो",
    "p:तीन चीज़ें जाँचें: फॉर्मैट सही है (JPG बनाम PNG), साइज़ लिमिट के <em>अंदर</em> है (कुछ फॉर्म “20 KB से ज़्यादा” भी मांगते हैं — तब टारगेट 40 KB रखें), और लंबाई-चौड़ाई पिक्सेल में वही है जो फॉर्म चाहता है। आखिरी वाले के लिए <a href=\"/passport-photo/\">पासपोर्ट फोटो टूल</a> सही शेप में काटता भी है।"
   ]
  },
  {
   "slug": "pdf-ka-size-kam-kaise-kare",
   "lang": "hi",
   "cat": "PDF",
   "fam": "doc",
   "title": "PDF का साइज़ कम कैसे करें — 100 KB, 200 KB या 500 KB में",
   "seo_title": "PDF का साइज़ कम कैसे करें (100–500 KB)",
   "teaser": "डॉक्युमेंट स्कैन किया, PDF 3 MB की बन गई, और पोर्टल 200 KB से ऊपर लेता ही नहीं। बिना ऐप और बिना अपलोड, इसे लिमिट में लाने का तरीका।",
   "alt": null,
   "tryTool": "compress-pdf",
   "tryLabel": "PDF का साइज़ अभी कम करें",
   "body": [
    "p:आधार, मार्कशीट, सर्टिफिकेट — फोन से स्कैन करते ही PDF कई MB की बन जाती है, क्योंकि उसके अंदर असल में एक बड़ी फोटो होती है। और सरकारी पोर्टल, स्कॉलरशिप साइट, नौकरी के फॉर्म 100, 200 या 500 KB की लिमिट रखते हैं।",
    "h:PDF बड़ी क्यों होती है",
    "p:दो तरह की PDF होती हैं। एक जिसमें असली टेक्स्ट है (Word से बनी) — वह वैसे ही छोटी होती है। दूसरी जिसमें पन्नों की <em>तस्वीर</em> है (स्कैन या फोटो से बनी) — यही भारी होती है, और इसे छोटा करने का एक ही तरीका है: तस्वीर को छोटा करना।",
    "h:टारगेट लिखो, PDF डालो",
    "p:<a href=\"/compress-pdf/\">Compress PDF</a> टूल में KB में लिमिट लिखिए और फाइल डाल दीजिए। “Strong” मोड हर पन्ने को नई, हल्की तस्वीर की तरह दोबारा बनाता है — पहले ऊँची क्वालिटी पर कोशिश करता है, फिर तब तक घटाता है जब तक पूरी फाइल लिमिट में न आ जाए। स्कैन की हुई PDF के लिए यही सही तरीका है।",
    "p:PDF आपके ब्राउज़र के अंदर ही खुलती और बनती है। सर्टिफिकेट और पहचान-पत्र जैसे निजी दस्तावेज़ किसी सर्वर पर नहीं जाते।",
    "h:Strong और Light में क्या फर्क है",
    "p:Strong में पन्ने तस्वीर बन जाते हैं, इसलिए बाद में उनमें टेक्स्ट सेलेक्ट या सर्च नहीं हो सकता — फॉर्म अपलोड के लिए इससे कोई फर्क नहीं पड़ता। Light मोड फाइल की अंदरूनी बनावट साफ करता है और टेक्स्ट को टेक्स्ट ही रहने देता है, लेकिन स्कैन की हुई PDF को यह ज़्यादा छोटा नहीं कर पाता, क्योंकि उसमें छोटा करने को टेक्स्ट है ही नहीं।",
    "h:200 KB में पन्ना पढ़ने लायक रहेगा?",
    "p:एक-दो पन्नों का सर्टिफिकेट 200 KB में आराम से साफ रहता है। दस पन्नों की मार्कशीट 200 KB में थोड़ी धुंधली हो सकती है — तब टूल आपको सबसे छोटा <em>पढ़ने लायक</em> वर्ज़न देता है और साथ में बता देता है कि लिमिट पूरी नहीं हुई। ऐसे में या तो लिमिट बढ़ाइए, या PDF को <a href=\"/split-pdf/\">दो हिस्सों में बाँट</a> लीजिए।",
    "h:पहले से छोटी PDF बनाने की ट्रिक",
    "p:स्कैन करते समय ही रंगीन की जगह “ग्रेस्केल” या “डॉक्युमेंट” मोड चुनें और रेज़ोल्यूशन 150–200 dpi रखें। इससे PDF शुरू से ही चार-पाँच गुना हल्की बनती है। और अगर आपके पास पन्नों की अलग-अलग फोटो हैं, तो <a href=\"/images-to-pdf/\">Images to PDF</a> टूल से सीधे एक हल्की PDF बना लीजिए।",
    "h:मोबाइल पर",
    "p:फोन के ब्राउज़र में यही टूल खुलता है। Files ऐप से PDF चुनिए, साइज़ लिखिए, Compress दबाइए। Downloads में नई फाइल आ जाती है, पुरानी वैसी की वैसी रहती है।"
   ]
  },
  {
   "slug": "passport-size-photo-kaise-banaye",
   "lang": "hi",
   "cat": "इमेज",
   "fam": "image",
   "title": "पासपोर्ट साइज़ फोटो कैसे बनाएं — मोबाइल से, फ्री में",
   "seo_title": "पासपोर्ट साइज़ फोटो कैसे बनाएं (35×45 mm)",
   "teaser": "फोटो स्टूडियो जाने की ज़रूरत नहीं। फोन से खींची किसी भी फोटो को सही साइज़ (35×45 mm) में काटिए, 50 KB से नीचे रखिए, और प्रिंट के लिए एक शीट बनाइए।",
   "alt": null,
   "tryTool": "passport-photo",
   "tryLabel": "पासपोर्ट फोटो अभी बनाएं",
   "body": [
    "p:पासपोर्ट, PAN, वीज़ा, एग्ज़ाम फॉर्म, नौकरी का आवेदन — सबको “पासपोर्ट साइज़” फोटो चाहिए, और उसका मतलब भारत में लगभग हमेशा एक ही है: 35 मिलीमीटर चौड़ी, 45 मिलीमीटर ऊँची, हल्के रंग की सादी बैकग्राउंड, और चेहरा फ्रेम का ज़्यादातर हिस्सा।",
    "h:फोटो कैसे खींचें",
    "p:किसी सादी, हल्के रंग की दीवार के सामने खड़े हों (सफ़ेद या हल्का क्रीम सबसे अच्छा)। रोशनी सामने से आए, पीछे से नहीं — खिड़की की तरफ़ मुँह करके खड़े होना सबसे आसान है। कैमरा आँखों की ऊँचाई पर, सीधे सामने। चेहरा सीधा, सामान्य भाव, आँखें खुली, चश्मा हो तो चमक न आए। किसी दूसरे से खिंचवाएँ या टाइमर लगाएँ; सेल्फ़ी में चेहरा थोड़ा बिगड़ता है।",
    "h:सही साइज़ में काटना",
    "p:<a href=\"/passport-photo/\">Passport Photo</a> टूल में फोटो डालिए। “India · 35×45 mm” पहले से चुना होता है। फोटो को खींचकर और ज़ूम करके ऐसे रखिए कि चेहरा पीली डॉटेड लाइन में आ जाए — सिर फ्रेम की ऊँचाई का लगभग 70%, आँखें ऊपर से एक-तिहाई पर। यही वह अनुपात है जो पासपोर्ट ऑफिस और ज़्यादातर फॉर्म चाहते हैं।",
    "p:फोटो 300 dpi पर बनती है, यानी प्रिंट क्वालिटी। और यह आपके फोन के अंदर ही बनती है — कहीं अपलोड नहीं होती।",
    "h:ऑनलाइन फॉर्म के लिए: 50 KB से नीचे",
    "p:अगर फॉर्म फाइल साइज़ की लिमिट रखता है, तो “Max file size” में वह नंबर लिख दीजिए — 50, 100, जो भी हो। फोटो उसी लिमिट के नीचे, सबसे अच्छी क्वालिटी में सेव होती है। अलग से कंप्रेस करने की ज़रूरत नहीं।",
    "h:प्रिंट के लिए: एक शीट में 8 फोटो",
    "p:“4×6 inch print sheet” टिक रहने दें। आपको दूसरी फाइल मिलती है जिसमें 4×6 इंच के कागज़ पर 8 फोटो कटिंग लाइन के साथ लगी हैं। इसे किसी भी फोटो शॉप पर “4×6 प्रिंट, 100% साइज़, फिट-टू-पेज नहीं” कहकर प्रिंट करवाइए, या घर के प्रिंटर पर फोटो पेपर पर निकालिए। ग्रे लाइनों पर काट लीजिए।",
    "h:दूसरे देशों के साइज़",
    "p:अमेरिका 2×2 इंच (51×51 mm) मांगता है, कनाडा 50×70 mm, चीन 33×48 mm, UK और यूरोप भारत की तरह 35×45 mm। ये सब टूल में प्रीसेट हैं; अपने फॉर्म की ज़रूरत के हिसाब से चुन लें, या “Custom” में मिलीमीटर लिख दें।",
    "h:बैकग्राउंड सफ़ेद नहीं है तो?",
    "p:यह टूल फोटो को काटता और नापता है, बैकग्राउंड नहीं बदलता। इसलिए सादी हल्की दीवार के सामने फोटो खींचना ही सबसे भरोसेमंद रास्ता है — “सफ़ेद बैकग्राउंड” का मतलब ज़्यादातर फॉर्म में “सादी और हल्की” होता है, बिल्कुल सफ़ेद नहीं।"
   ]
  },
  {
   "slug": "heic-ko-jpg-me-kaise-badle",
   "lang": "hi",
   "cat": "इमेज",
   "fam": "image",
   "title": "iPhone की HEIC फोटो को JPG में कैसे बदलें",
   "seo_title": "HEIC को JPG में कैसे बदलें",
   "teaser": "iPhone से भेजी फोटो Windows या Android पर खुल नहीं रही? फाइल HEIC है। एक क्लिक में JPG बनाइए, बिना ऐप और बिना अपलोड के।",
   "alt": "heic-to-jpg",
   "tryFrom": "heic",
   "tryTo": "jpg",
   "tryLabel": "HEIC को JPG में अभी बदलें",
   "body": [
    "p:2017 से हर iPhone अपनी फोटो HEIC फॉर्मैट में सेव करता है। यह अच्छा फॉर्मैट है — वही फोटो आधी जगह में — लेकिन इसका एक बड़ा नुकसान है: Windows का कंप्यूटर, ज़्यादातर Android फोन, कई वेबसाइटें और लगभग हर सरकारी पोर्टल इसे खोल ही नहीं पाते। फोटो सही है, बस उसे कोई पढ़ नहीं पा रहा।",
    "h:Windows और Android इसे क्यों नहीं खोलते",
    "p:HEIC के अंदर फोटो HEVC नाम की तकनीक से दबी होती है, जिस पर पेटेंट हैं। Windows में इसे खोलने के लिए Microsoft Store से पैसे वाला “HEVC Video Extensions” लेना पड़ता है। Android 9 के बाद फोन तो इसे समझते हैं, पर हर ऐप नहीं। Chrome और Firefox इसे बिल्कुल नहीं खोलते — सिर्फ़ Safari खोलता है।",
    "h:एक कदम का हल",
    "p:<a href=\"/heic-to-jpg/\">HEIC to JPG</a> पेज पर फोटो डालिए और Convert दबाइए। JPG हर उस डिवाइस पर खुलती है जो पिछले पच्चीस साल में बनी है। एक साथ पूरी गैलरी भी डाल सकते हैं — सब फोटो एक-एक करके बदलती हैं और zip में मिलती हैं।",
    "p:Convert Files में HEIC खोलने का अपना डिकोडर है, इसलिए यह Windows के Chrome में भी काम करता है, जहाँ खुद ब्राउज़र HEIC नहीं खोल पाता। और फोटो कहीं अपलोड नहीं होती — सब आपके डिवाइस पर होता है।",
    "h:iPhone पर ही यह सेटिंग बदल दें",
    "p:अगर आप चाहते हैं कि iPhone आगे से HEIC बनाए ही नहीं: Settings › Camera › Formats › Most Compatible। इसके बाद कैमरा सीधे JPG सेव करेगा। फोटो थोड़ी ज़्यादा जगह लेंगी, लेकिन कहीं भी खुलेंगी। पहले से खिंची फोटो वैसी ही रहेंगी — उनके लिए ऊपर वाला टूल।",
    "h:क्वालिटी का क्या होगा",
    "p:HEIC से JPG में जाना दो “लॉसी” फॉर्मैट के बीच जाना है, इसलिए क्वालिटी 90% या ऊपर रखें — फर्क आँख से नहीं दिखेगा। जो फोटो आगे एडिट करनी हो, उसके लिए JPG की जगह PNG चुनें; वह लॉसलेस है।",
    "h:WhatsApp पर भेजते समय",
    "p:WhatsApp iPhone से भेजी HEIC को अपने आप JPG बना देता है, इसलिए वहाँ दिक्कत नहीं आती। दिक्कत तब आती है जब फोटो ईमेल, Google Drive, USB या AirDrop से Windows पर जाती है — तब वह HEIC ही रहती है। ऐसे में भेजने से पहले ही JPG बना लीजिए।"
   ]
  }
 ],
 "SUPPORT": {
  "upiId": "yogi1206@ptyes",
  "payeeName": "YOGESH BISHT",
  "qr": "/assets/upi-qr.png",
  "blurb": [
   "Convert Files is free, has no account and never uploads your files. It is built and kept running by one person.",
   "If it saved you an upload, a subscription or an afternoon, you can leave a small tip with any UPI app. Nothing is expected, and nothing changes if you do not."
  ]
 },
 "SPONSOR": {
  "name": "",
  "url": "",
  "tagline": "",
  "contact": ""
 }
}; })(window);
