#!/usr/bin/env python3
"""Build the production site in place.

    python3 build.py

Reads site.json and:
  - generates js/content.js from content/*.json
  - stamps the AdSense / analytics tags and window.SITE into index.html and admin/ (site:head block)
  - versions the CSS/JS URLs with a content hash
  - writes privacy.html, terms.html, contact.html, 404.html from pages/
  - writes one static page per popular conversion (/heic-to-jpg/) and per guide (/guides/<slug>/)
  - writes sitemap.xml, robots.txt, ads.txt and CNAME
Everything is idempotent: run it again after any edit, then commit.
"""
import datetime, hashlib, json, os, re, sys, html

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'seo'))
import formats as SEO          # noqa: E402
import pages as PAGES          # noqa: E402
import keywords as KW          # noqa: E402
import toolpages as TOOLPAGES  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
os.chdir(ROOT)
SITE = json.load(open('site.json'))
DOMAIN = SITE['domain'].rstrip('/')
HOST = re.sub(r'^https?://', '', DOMAIN)
TODAY = datetime.date.today().strftime('%d %B %Y')
GENERATED = []                                           # (path, lastmod) for the sitemap


def esc(s):
    return html.escape(str(s), quote=True)


# --------------------------------------------------------------- content
# Editorial content lives in content/*.json (what the admin panel edits).
# build.py turns it into js/content.js for the app and uses it for the pages.
def load_json(name):
    return json.load(open(os.path.join('content', name + '.json')))


CONTENT = {
    'POPULAR': [[p['from'], p['to'], p['label']] for p in load_json('popular')],
    'STEPS': [[s['title'], s['text']] for s in load_json('steps')],
    'FAQ': [[f['q'], f['a']] for f in load_json('faq')],
    'ABOUT': load_json('about'),
    'GUIDES': load_json('guides'),
    'SUPPORT': load_json('support'),
    'SPONSOR': load_json('sponsor'),
}
open('js/content.js', 'w').write(
    '/* content.js — GENERATED by build.py from content/*.json. Edit the JSON (or use /admin), not this file. */\n'
    '(function (root) { root.Content = ' + json.dumps(CONTENT, ensure_ascii=False, indent=1) + '; })(window);\n')


def parse_ext_table():
    """Format metadata from js/formats.js (the app's single source of truth)."""
    src = open('js/formats.js').read()
    body = src[src.index('var EXT = {'):src.index('};', src.index('var EXT = {'))]
    out = {}
    for m in re.finditer(r"(\w+):\['(\w+)','((?:[^'\\]|\\.)*)','([^']*)'\]", body):
        out[m.group(1)] = [m.group(2), m.group(3).replace("\\'", "'"), m.group(4)]
    if len(out) < 60:
        sys.exit('could not parse the EXT table in js/formats.js')
    return out


EXT = parse_ext_table()


def fmt_name(ext):
    return EXT.get(ext, [None, ext.upper()])[1]


def family(ext):
    return EXT.get(ext, ['any'])[0]


# ------------------------------------------------------------- asset version
def asset_version():
    h = hashlib.sha1()
    for f in sorted(os.listdir('js')) + ['app.css', 'tools.css']:
        p = os.path.join('js', f) if f.endswith('.js') else os.path.join('css', f)
        h.update(open(p, 'rb').read())
    return h.hexdigest()[:8]


VER = asset_version()


# ------------------------------------------------------------------ site head
def site_head():
    ads = SITE.get('adsense_client', '').strip()
    ga = SITE.get('ga4_measurement_id', '').strip()
    cfg = {'domain': DOMAIN, 'contact': SITE.get('contact_email', ''), 'api': SITE.get('api_base', '').rstrip('/'),
           'ads': {'client': ads, 'slots': SITE.get('adsense_slots', {})} if ads else None}
    lines = ['<script>window.SITE = ' + json.dumps(cfg) + ';</script>']
    # Search Console / Bing Webmaster verification. Paste the content value of
    # the <meta> tag they give you into site.json and rebuild.
    gsv = SITE.get('google_site_verification', '').strip()
    if gsv:
        lines.insert(0, '<meta name="google-site-verification" content="%s">' % esc(gsv))
    bsv = SITE.get('bing_site_verification', '').strip()
    if bsv:
        lines.insert(0, '<meta name="msvalidate.01" content="%s">' % esc(bsv))
    if ads:
        lines.append('<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=%s" crossorigin="anonymous"></script>' % ads)
    if ga:
        lines.append('<script async src="https://www.googletagmanager.com/gtag/js?id=%s"></script>' % ga)
        lines.append("<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','%s',{anonymize_ip:true});</script>" % ga)
    return '\n'.join(lines)


def replace_block(text, name, inner):
    start, end = '<!-- %s -->' % name, '<!-- /%s -->' % name
    a, b = text.index(start), text.index(end)
    return text[:a + len(start)] + '\n' + inner + '\n' + text[b:]


def page_meta(title, description, path, kind='website', extra_meta='', jsonld=None):
    url = DOMAIN + '/' + path
    m = ['<title>%s</title>' % esc(title),
         '<meta name="description" content="%s">' % esc(description),
         '<link rel="canonical" href="%s">' % esc(url),
         '<meta property="og:title" content="%s">' % esc(title),
         '<meta property="og:description" content="%s">' % esc(description),
         '<meta property="og:url" content="%s">' % esc(url),
         '<meta property="og:image" content="%s/assets/og.png">' % DOMAIN,
         '<meta property="og:type" content="%s">' % kind,
         '<meta property="og:site_name" content="Convert Files">',
         '<meta name="twitter:card" content="summary_large_image">',
         '<meta name="twitter:title" content="%s">' % esc(title),
         '<meta name="twitter:description" content="%s">' % esc(description),
         '<meta name="twitter:image" content="%s/assets/og.png">' % DOMAIN,
         '<meta name="twitter:image:alt" content="Convert Files — free file converter that runs in your browser">']
    if extra_meta:
        m.append(extra_meta)
    for block in (jsonld if isinstance(jsonld, list) else [jsonld] if jsonld else []):
        m.append('<script type="application/ld+json">' + json.dumps(block, ensure_ascii=False) + '</script>')
    return '\n'.join(m)


def clip(text, budget):
    """Trim to `budget` characters on a word boundary — never mid-word."""
    text = ' '.join(text.split())
    if len(text) <= budget:
        return text
    cut = text[:budget + 1]
    sp = cut.rfind(' ')
    return cut[:sp].rstrip(' ,;:-\u2014') if sp > 0 else ''


def meta_desc(F, T, why, what):
    """A unique <=158-char description per pair: fixed promise + a whole
    sentence of pair-specific copy that fits, rather than a truncated one."""
    head = 'Convert %s to %s free in your browser. Nothing is uploaded. ' % (F, T)
    budget = 157 - len(head)
    cands = []
    for sentence in re.split(r'(?<=[.!?])\s+', why):
        sentence = sentence.strip()
        if not sentence:
            continue
        cands.append(sentence)
        # ...and the halves of a two-clause "because A, while B." sentence,
        # either of which stands on its own in a search snippet.
        for part in re.split(r',\s+while\s+', sentence):
            part = part.strip().rstrip('.')
            part = re.sub(r'^People convert \S+ to \S+ because ', '', part)
            if part:
                cands.append(part[0].upper() + part[1:] + '.')
    cands.sort(key=lambda c: -len(c))
    # `what` is shared by every pair in the family, so it is only a last resort
    cands += sorted((x.strip() for x in re.split(r'(?<=[.!?])\s+', what) if x.strip()), key=lambda c: -len(c))
    tail = next((c for c in cands if len(c) <= budget), '')
    if not tail and cands:
        tail = (clip(cands[0].split(',')[0], budget - 1) + '.').strip()
    return (head + tail).strip()


def hide_converter(page):
    """A hub page lists what you can convert; it is not itself a converter.
    The markup stays (app.js expects every one of these elements to exist) but
    the file picker and the format chooser are not shown."""
    out = page.replace('<div class="drop" id="drop"', '<div class="drop" id="drop" hidden')
    out = out.replace('<div class="section">', '<div class="section" hidden>', 1)
    assert out != page, 'converter markup not found'
    return out


def strip_home(page):
    """Generated pages keep the converter and their own content, not the home
    page's editorial blocks — 400 copies of the same FAQ helps nobody. The
    tools rail beside the converter is the home page's too."""
    for start, end in (('<!-- home:only -->', '<!-- /home:only -->'), ('<!-- rail:only -->', '<!-- /rail:only -->'), ('<!-- promo:only -->', '<!-- /promo:only -->')):
        a, b = page.find(start), page.find(end)
        if a >= 0 and b >= 0:
            page = page[:a] + page[b + len(end):]
    return page.replace('<div class="convert-grid two">', '<div class="convert-grid">', 1)


def write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    open(path, 'w').write(text)
    GENERATED.append(path)


# ------------------------------------------------------------ index.html base
index = open('index.html').read()
index = re.sub(r'\?v=[0-9a-f]+', '?v=' + VER, index)
index = replace_block(index, 'site:head', site_head())
home_jsonld = {
    '@context': 'https://schema.org', '@type': 'WebApplication', 'name': 'Convert Files', 'url': DOMAIN + '/',
    'applicationCategory': 'UtilitiesApplication', 'operatingSystem': 'Any', 'browserRequirements': 'Requires a modern browser',
    'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'INR'},
    'description': 'Free online file converter that runs entirely in your browser. Images, PDF, Word, Excel, audio, video, fonts and 3D models. Nothing is uploaded.'
}
index = replace_block(index, 'page:meta', page_meta(
    'Free Online File Converter \u2014 Nothing Uploaded | Convert Files',
    'Free online file converter for images, PDF, Word, Excel, audio, video, fonts and 3D models \u2014 converted in your browser in seconds. No upload, no account.',
    '', jsonld=home_jsonld))
index = replace_block(index, 'page:body', '')


def chip_html(ext):
    fam = family(ext)
    return '<span class="chip" style="--fam:var(--f-%s)">.%s</span>' % (fam, ext)


# Static, crawlable versions of the two link lists the app would otherwise build
# in JavaScript. The app leaves them alone when they are already filled.
_pop = []
for _p in load_json('popular'):
    _pop.append('<a href="/%s-to-%s/">%s<span style="color:var(--pop)">&rarr;</span>%s<span class="lbl">%s</span></a>'
                % (_p['from'], _p['to'], chip_html(_p['from']), chip_html(_p['to']), esc(_p['label'])))
index = replace_block(index, 'popular:tiles', ''.join(_pop))

# every tool, one per row, most wanted first; app.js reorders by real usage
_rail = ['<div class="rail-h"><h2>Tools</h2><span class="rail-tag">Most used</span></div><ol class="rail-list">']
_by = {x['slug']: x for x in TOOLPAGES.TOOLS}
for _i, _slug in enumerate(TOOLPAGES.RAIL_ORDER):
    _t = _by[_slug]
    _hint, _icon = TOOLPAGES.RAIL_META[_slug]
    _rail.append('<li%s><a href="/%s/" data-tool="%s">'
                 '<span class="ic" style="--fam:var(--f-%s)"><svg><use href="#t-%s"/></svg></span>'
                 '<span class="tx"><b>%s</b><small>%s<i class="cnt" hidden></i></small></span><span class="rk">%02d</span></a></li>'
                 % (' class="more"' if _i >= 11 else '', _slug, _slug, TOOLPAGES.GROUP_FAM[_t['group']], _icon, esc(_t['name']), esc(_hint), _i + 1))
_rail.append('</ol><div class="rail-foot"><button type="button" class="rail-more" id="rail-more" aria-expanded="false">View all %d tools</button></div>' % len(TOOLPAGES.TOOLS))
index = replace_block(index, 'rail:list', ''.join(_rail))

# the banner rotates through what the site does: popular conversions and tools, interleaved
_conv = [(p['from'], p['to'], p['label']) for p in load_json('popular')]
_tools = [(sl, _by[sl]) for sl in TOOLPAGES.RAIL_ORDER]
_slides, _ci, _ti = [], 0, 0
while _ci < len(_conv) or _ti < len(_tools):
    if _ci < len(_conv):
        f, tt, lab = _conv[_ci]; _ci += 1
        _slides.append('<a class="promo-slide%s" href="/%s-to-%s/"><span class="promo-ic" style="--fam:var(--f-%s)"><svg><use href="#i-swap"/></svg></span>'
                       '<div><b>%s</b><p>Convert %s to %s free, in your browser &mdash; nothing uploaded</p></div></a>'
                       % (' on' if not _slides else '', f, tt, family(f), esc(lab), f.upper(), tt.upper()))
    if _ti < len(_tools):
        sl, tool = _tools[_ti]; _ti += 1
        _hint, _icon = TOOLPAGES.RAIL_META[sl]
        _slides.append('<a class="promo-slide%s" href="/%s/"><span class="promo-ic" style="--fam:var(--f-%s)"><svg><use href="#t-%s"/></svg></span>'
                       '<div><b>%s</b><p>%s &mdash; free, nothing uploaded</p></div></a>'
                       % (' on' if not _slides else '', sl, TOOLPAGES.GROUP_FAM[tool['group']], _icon, esc(tool['name']), esc(_hint)))
index = replace_block(index, 'promo:slides', ''.join(_slides))
_gc = []
for _g in [g for g in CONTENT['GUIDES'] if g.get('lang') != 'hi'][:3]:
    _words = len(re.sub(r'<[^>]+>', '', ' '.join(_g['body'])).split())
    _gc.append('<a class="gcard" href="/guides/%s/"><span class="cat" style="--fam:var(--f-%s)">%s</span>'
               '<h3>%s</h3><p>%s</p><span class="rt">%d min read</span></a>'
               % (_g['slug'], _g['fam'], esc(_g['cat']), esc(_g['title']), esc(_g['teaser']), max(2, round(_words / 200))))
index = replace_block(index, 'home:guides', ''.join(_gc))
open('index.html', 'w').write(index)
GENERATED.append('index.html')
BASE = index



# ---------------------------------------------------------- landing pages
GRAPH = json.load(open('content/pairs.json'))['graph']
SEO_PAIRS = SEO.seo_pairs(GRAPH)

# shared by the tool pages, the guides and the hubs
TOOL_BY_SLUG = {t['slug']: t for t in TOOLPAGES.all_pages()}
LANDING_SLUGS = set('%s-to-%s' % p for p in SEO_PAIRS)
HERO_P = '<p>Convert any file, right here &mdash; pick a file, choose what it should become, download the result. Everything runs inside your browser; nothing is uploaded.</p>'
PAIR_SET = set(SEO_PAIRS)


def crumbs(items):
    """Visible breadcrumb trail plus its structured data."""
    trail = ' <span aria-hidden="true">&rsaquo;</span> '.join(
        ('<a href="%s">%s</a>' % (esc(u), esc(n))) if u else ('<span>%s</span>' % esc(n)) for n, u in items)
    ld = {'@context': 'https://schema.org', '@type': 'BreadcrumbList', 'itemListElement': [
        {'@type': 'ListItem', 'position': i + 1, 'name': n, **({'item': DOMAIN + u} if u else {})}
        for i, (n, u) in enumerate(items)]}
    return '<nav class="crumbs" aria-label="Breadcrumb">%s</nav>' % trail, ld


for f, t in SEO_PAIRS:
    F, T = f.upper(), t.upper()
    path = '%s-to-%s/' % (f, t)
    fname, tname = PAGES.name_of(f, EXT), PAGES.name_of(t, EXT)
    why = PAGES.reason(f, t, EXT)
    what = PAGES.expect(f, t, EXT)
    qa = PAGES.faqs(f, t, EXT)
    group_title, group_fam = PAGES.group_of(f)

    SF, ST = KW.search_name(f), KW.search_name(t)               # "Word", not "DOCX"
    title = '%s to %s Converter \u2014 free, online, nothing uploaded' % (SF, ST)
    # the H1 carries the exact extension too, so "PDF to Word (DOCX) converter"
    h1 = '%s to %s converter' % (SF + (' (%s)' % F if SF != F else ''), ST + (' (%s)' % T if ST != T else ''))
    desc = meta_desc(F, T, why, what)
    crumb_html, crumb_ld = crumbs([('Home', '/'), (group_title, '/formats/'), ('%s to %s' % (F, T), None)])

    steps = [
        ('Choose your %s file' % F, 'Drop it on the box above, or tap to browse. You can pick several files at once.'),
        ('Confirm the target is .%s' % t, 'It is already selected. Adjust quality, size or the other options if you want to.'),
        ('Convert and download', 'Press Convert, then Download. Your file stays on your device the whole time.'),
    ]

    body = ['<section class="seo">', crumb_html,
            '<h2>Why convert %s to %s?</h2><p>%s</p>' % (F, T, esc(why)),
            '<h2>How to convert %s to %s</h2><ol class="howto">' % (F, T)]
    for st, sd in steps:
        body.append('<li><strong>%s.</strong> %s</li>' % (esc(st), esc(sd)))
    body.append('</ol>')
    for ext_ in (f, t):
        info = SEO.FORMATS.get(ext_)
        if info:
            body.append('<h2>What is a .%s file?</h2><p>%s</p>' % (ext_, esc(info['blurb'])))
    body.append('<h2>What to expect from this conversion</h2><p>%s</p>' % esc(what))
    body.append('<h2>Is it private?</h2><p>Yes, by design. Every conversion happens inside your own browser using your '
                'device\u2019s processor \u2014 there is no server that receives your %s file, so there is nothing for anyone '
                'to store, scan or leak. You can confirm it yourself: open your browser\u2019s developer tools, watch the '
                'Network tab while you convert, and you will see no upload.</p>' % F)
    body.append('<h2>Questions about %s to %s</h2><dl class="faq-list">' % (F, T))
    for q, a in qa:
        body.append('<dt>%s</dt><dd>%s</dd>' % (esc(q), esc(a)))
    body.append('</dl>')

    rel = PAGES.related(f, t, PAIR_SET)
    if rel:
        body.append('<h2>Related conversions</h2><div class="rel">' + ''.join(
            '<a href="/%s-to-%s/">%s to %s</a>' % (a, b, a.upper(), b.upper()) for a, b in rel) + '</div>')
    body.append('<p class="seo-more"><a href="/formats/">See all %s conversions</a> &middot; '
                '<a href="/guides/">Read the guides</a></p>' % len(SEO_PAIRS))
    body.append('</section>')

    howto_ld = {'@context': 'https://schema.org', '@type': 'HowTo',
                'name': 'How to convert %s to %s' % (F, T),
                'description': 'Convert a %s file to %s in a browser, without uploading it anywhere.' % (F, T),
                'totalTime': 'PT1M', 'supply': [{'@type': 'HowToSupply', 'name': 'A %s file' % F}],
                'tool': [{'@type': 'HowToTool', 'name': 'A web browser'}],
                'step': [{'@type': 'HowToStep', 'position': i + 1, 'name': st, 'text': sd,
                          'url': '%s/%s#step%d' % (DOMAIN, path, i + 1)} for i, (st, sd) in enumerate(steps)]}
    faq_ld = {'@context': 'https://schema.org', '@type': 'FAQPage',
              'mainEntity': [{'@type': 'Question', 'name': q,
                              'acceptedAnswer': {'@type': 'Answer', 'text': a}} for q, a in qa]}
    meta = page_meta(title, desc, path,
                     extra_meta='<meta name="cf-preset" content="%s>%s">' % (f, t),
                     jsonld=[crumb_ld, howto_ld, faq_ld])
    page = replace_block(BASE, 'page:meta', meta)
    page = replace_block(page, 'page:body', '\n'.join(body))
    page = page.replace('<h1>Free Online File Converter</h1>', '<h1>%s</h1>' % esc(h1))
    page = page.replace('<p>Convert any file, right here &mdash; pick a file, choose what it should become, download the result. Everything runs inside your browser; nothing is uploaded.</p>',
                        '<p>Convert %s to %s free, in your browser, in seconds &mdash; nothing uploaded anywhere.</p>' % (esc(fname), esc(tname)))
    write(path + 'index.html', strip_home(page))


# ------------------------------------------------------------- hub page
hub = ['<section class="seo hub">']
hub_crumb, hub_crumb_ld = crumbs([('Home', '/'), ('All conversions', None)])
hub.append(hub_crumb)
hub.append('<p class="lead">Every conversion below has its own page with step-by-step instructions, an explanation of both '
           'formats and answers to the questions people ask. All of them run inside your browser \u2014 nothing is uploaded.</p>')
by_source = {}
for f, t in SEO_PAIRS:
    by_source.setdefault(f, []).append(t)
for group_title, fam, members in SEO.GROUPS:
    present = [m for m in members if m in by_source]
    if not present:
        continue
    hub.append('<h2 id="%s">%s</h2>' % (fam, group_title))
    for src in present:
        hub.append('<div class="hub-row"><b>From .%s</b><div class="rel">%s</div></div>' % (
            src, ''.join('<a href="/%s-to-%s/">%s to %s</a>' % (src, tt, src.upper(), tt.upper())
                         for tt in sorted(by_source[src]))))
hub.append('</section>')
hub_page = replace_block(BASE, 'page:meta', page_meta(
    'All file conversions \u2014 %d free converters, nothing uploaded' % len(SEO_PAIRS),
    'Every conversion Convert Files supports — PNG to JPG, PDF to Word, MOV to MP4 and 396 more, each with its own guide. Free, nothing uploaded.', 'formats/', jsonld=[hub_crumb_ld]))
hub_page = replace_block(hub_page, 'page:body', '\n'.join(hub))
hub_page = hub_page.replace('<h1>Free Online File Converter</h1>', '<h1>All conversions</h1>')
hub_page = hub_page.replace('<p>Convert any file, right here &mdash; pick a file, choose what it should become, download the result. Everything runs inside your browser; nothing is uploaded.</p>',
                            '<p>%d conversions, each with its own page. Pick the one you need and convert it there.</p>' % len(SEO_PAIRS))
write('formats/index.html', hide_converter(strip_home(hub_page)))

# ------------------------------------------------------------- guide pages
def render_body(lines):
    out = []
    for line in lines:
        kind, text = line[:1], line[2:]
        if line.startswith('ul:'):
            out.append('<ul>' + ''.join('<li>%s</li>' % t for t in line[3:].split('|')) + '</ul>')
        elif kind == 'h':
            out.append('<h2>%s</h2>' % text)
        else:
            out.append('<p>%s</p>' % text)
    return '\n'.join(out)


GUIDE_BY_SLUG = {g['slug']: g for g in CONTENT['GUIDES']}


def guide_path(g):
    return ('hi/guides/%s/' if g.get('lang') == 'hi' else 'guides/%s/') % g['slug']


def hreflang_links(g):
    """<link rel=alternate> pairs when a guide exists in both languages."""
    other = GUIDE_BY_SLUG.get(g.get('alt') or '')
    if not other:
        return ''
    en, hi = (other, g) if g.get('lang') == 'hi' else (g, other)
    return ('<link rel="alternate" hreflang="en" href="%s/%s">' % (DOMAIN, guide_path(en)) +
            '<link rel="alternate" hreflang="hi" href="%s/%s">' % (DOMAIN, guide_path(hi)) +
            '<link rel="alternate" hreflang="x-default" href="%s/%s">' % (DOMAIN, guide_path(en)))


for gd in CONTENT['GUIDES']:
    path = guide_path(gd)
    hindi = gd.get('lang') == 'hi'
    words = len(re.sub(r'<[^>]+>', '', ' '.join(gd['body'])).split())
    article = ['<div class="cat">%s</div>' % esc(gd['cat']), '<h1>%s</h1>' % esc(gd['title']),
               '<div class="meta">%s</div>' % (('%d मिनट में पढ़ें · Convert Files' % max(2, round(words / 180))) if hindi else ('%d min read · Convert Files guides' % max(2, round(words / 200)))),
               '<div class="body">' + render_body(gd['body']) + '</div>']
    if gd.get('tryTool'):
        article.append('<div class="try"><span class="t">%s</span><a class="btn primary" href="/%s/">%s</a></div>'
                       % (esc(gd.get('tryLabel') or 'Try it — free, in your browser.'), gd['tryTool'], esc(TOOL_BY_SLUG[gd['tryTool']]['name'] if gd['tryTool'] in TOOL_BY_SLUG else gd['tryTool'])))
    elif gd.get('tryFrom'):
        article.append('<div class="try"><span class="t">%s</span><a class="btn primary" href="/%s-to-%s/">Convert .%s to .%s</a></div>'
                       % (esc(gd.get('tryLabel') or ('Try it: convert a .%s to .%s — free, in your browser.' % (gd['tryFrom'], gd['tryTo']))), gd['tryFrom'], gd['tryTo'], gd['tryFrom'], gd['tryTo']))
    guides_crumb = ('हिन्दी गाइड', '/hi/guides/') if hindi else ('Guides', '/guides/')
    _, gcrumb_ld = crumbs([('Home', '/'), guides_crumb, (gd['title'], None)])
    jsonld = [gcrumb_ld, {'@context': 'https://schema.org', '@type': 'Article', 'headline': gd['title'], 'description': gd['teaser'],
              'author': {'@type': 'Organization', 'name': 'Convert Files'}, 'publisher': {'@type': 'Organization', 'name': 'Convert Files'},
              'mainEntityOfPage': DOMAIN + '/' + path, 'image': DOMAIN + '/assets/og.png'}]
    page = replace_block(BASE, 'page:meta', page_meta(gd.get('seo_title', gd['title']) + ' \u00b7 Convert Files', gd['teaser'], path, kind='article',
                                                       extra_meta='<meta name="cf-guide" content="%s">' % gd['slug'] + hreflang_links(gd), jsonld=jsonld))
    if hindi:
        page = page.replace('<html lang="en">', '<html lang="hi">', 1)
    page = page.replace('<h1>Free Online File Converter</h1>',
                        '<p class="lede">Convert any file, right here.</p>')
    page = replace_block(page, 'page:body', '')
    # pre-render the article for crawlers; the app takes over on load
    page = page.replace('<section class="view" id="view-convert">', '<section class="view" id="view-convert" hidden>')
    page = page.replace('<section class="view" id="view-guides" hidden>', '<section class="view" id="view-guides">')
    page = page.replace('<div id="guides-list">', '<div id="guides-list" hidden>')
    page = page.replace('<article class="article" id="article" hidden></article>', '<article class="article" id="article">' + '\n'.join(article) + '</article>')
    page = page.replace('id="nav-convert" role="tab" aria-selected="true"', 'id="nav-convert" role="tab" aria-selected="false"')
    gc_html, gc_ld = crumbs([('Home', '/'), guides_crumb, (gd['title'], None)])
    page = page.replace('<article class="article" id="article">', '<article class="article" id="article">' + gc_html)
    write(path + 'index.html', strip_home(page))


# ------------------------------------------------------------ guides index
gi = ['<section class="seo">']
gi_crumb, gi_crumb_ld = crumbs([('Home', '/'), ('Guides', None)])
gi.append(gi_crumb)
gi.append('<p class="lead">Plain-language explanations of the file formats people wrestle with most, and what actually '
          'happens when you convert between them.</p>')
EN_GUIDES = [g for g in CONTENT['GUIDES'] if g.get('lang') != 'hi']
HI_GUIDES = [g for g in CONTENT['GUIDES'] if g.get('lang') == 'hi']
for gd in EN_GUIDES:
    gi.append('<article class="hub-guide"><h2><a href="/guides/%s/">%s</a></h2><p>%s</p></article>'
              % (gd['slug'], esc(gd['title']), esc(gd['teaser'])))
gi.append('<p class="seo-more"><a href="/hi/guides/" lang="hi">हिन्दी में गाइड पढ़ें</a></p>')
gi.append('</section>')
gi_page = replace_block(BASE, 'page:meta', page_meta(
    'Guides \u2014 file formats explained without the jargon',
    'Short, practical guides to HEIC, PDF and Word, image formats, video for the web, 3D models for AR, spreadsheets and '
    'privacy when converting files online.', 'guides/', jsonld=[gi_crumb_ld]))
gi_page = replace_block(gi_page, 'page:body', '\n'.join(gi))
gi_page = gi_page.replace('<h1>Free Online File Converter</h1>', '<h1>Guides</h1>')
gi_page = gi_page.replace('<p>Convert any file, right here &mdash; pick a file, choose what it should become, download the result. Everything runs inside your browser; nothing is uploaded.</p>',
                          '<p>%d guides to the formats people ask about most.</p>' % len(EN_GUIDES))
write('guides/index.html', hide_converter(strip_home(gi_page)))

# ---- /hi/guides/: the Hindi index
hg = ['<section class="seo">']
hg_crumb, hg_crumb_ld = crumbs([('Home', '/'), ('हिन्दी गाइड', None)])
hg.append(hg_crumb)
hg.append('<p class="lead">फोटो और PDF का साइज़ कम करना, पासपोर्ट फोटो बनाना, iPhone की फोटो खोलना — आसान हिन्दी में, बिना किसी ऐप के। सब कुछ आपके फोन या कंप्यूटर के ब्राउज़र में होता है; कोई फाइल अपलोड नहीं होती।</p>')
for gd in HI_GUIDES:
    hg.append('<article class="hub-guide"><h2><a href="/hi/guides/%s/">%s</a></h2><p>%s</p></article>' % (gd['slug'], esc(gd['title']), esc(gd['teaser'])))
hg.append('<p class="seo-more"><a href="/guides/">Guides in English</a> &middot; <a href="/tools/">सभी टूल</a></p>')
hg.append('</section>')
hg_page = replace_block(BASE, 'page:meta', page_meta('हिन्दी गाइड — फोटो, PDF और फाइल कन्वर्ट करने के आसान तरीके',
                                                    'फोटो का साइज़ कम करना, PDF छोटी करना, पासपोर्ट साइज़ फोटो बनाना और HEIC को JPG में बदलना — हिन्दी में, फ्री, बिना अपलोड।',
                                                    'hi/guides/', jsonld=[hg_crumb_ld],
                                                    extra_meta='<link rel="alternate" hreflang="en" href="%s/guides/"><link rel="alternate" hreflang="hi" href="%s/hi/guides/">' % (DOMAIN, DOMAIN)))
hg_page = hg_page.replace('<html lang="en">', '<html lang="hi">', 1)
hg_page = replace_block(hg_page, 'page:body', '\n'.join(hg))
hg_page = hg_page.replace('<h1>Free Online File Converter</h1>', '<h1>हिन्दी गाइड</h1>')
hg_page = hg_page.replace(HERO_P, '<p>%d गाइड, आसान हिन्दी में।</p>' % len(HI_GUIDES))
write('hi/guides/index.html', hide_converter(strip_home(hg_page)))

# ------------------------------------------------------------- tool pages
# /compress-image/, /merge-pdf/ and friends: the converter's shell, the drop
# zone, and <meta name="cf-tool"> so tools.js knows which tool to run.
TOOL_CSS = '<style>' + open('css/tools.css').read().replace('</style>', '') + '</style>'
TOOL_JS = '<script defer src="/js/tools.js?v=%s"></script>' % VER


def related_links(slugs):
    out = []
    for s in slugs:
        if s in TOOL_BY_SLUG:
            out.append('<a href="/%s/">%s</a>' % (s, esc(TOOL_BY_SLUG[s]['h1'] if TOOL_BY_SLUG[s].get('parent') else TOOL_BY_SLUG[s]['name'])))
        elif s in LANDING_SLUGS:
            f, t = s.split('-to-')
            out.append('<a href="/%s/">%s to %s</a>' % (s, f.upper(), t.upper()))
    return ''.join(out)


for t in TOOLPAGES.all_pages():
    path = t['slug'] + '/'
    tool_id = t.get('parent') or t['slug']
    extra = '<meta name="cf-tool" content="%s">' % tool_id
    if t.get('preset'):
        extra += '<meta name="cf-tool-preset" content="%s">' % esc(json.dumps(t['preset']))
    extra += '\n' + TOOL_CSS
    crumb_html, crumb_ld = crumbs([('Home', '/'), ('Tools', '/tools/'), (t['h1'], None)])
    steps = [s for s in t['steps'] if s[0]]
    howto_ld = {'@context': 'https://schema.org', '@type': 'HowTo', 'name': t['h1'], 'description': t['desc'],
                'tool': {'@type': 'HowToTool', 'name': 'Convert Files (any modern browser)'},
                'step': [{'@type': 'HowToStep', 'position': i + 1, 'name': s[0], 'text': s[1] or s[0]} for i, s in enumerate(steps)]}
    faq_ld = {'@context': 'https://schema.org', '@type': 'FAQPage',
              'mainEntity': [{'@type': 'Question', 'name': q, 'acceptedAnswer': {'@type': 'Answer', 'text': a}} for q, a in t['faq']]}
    app_ld = {'@context': 'https://schema.org', '@type': 'SoftwareApplication', 'name': t['h1'], 'applicationCategory': 'UtilitiesApplication',
              'operatingSystem': 'Any', 'browserRequirements': 'Requires a modern browser', 'url': DOMAIN + '/' + path,
              'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'INR'}, 'description': t['desc']}
    body = ['<section class="tool" id="tool" aria-label="%s"></section>' % esc(t['h1']),
            '<section class="seo">', crumb_html,
            '<p class="lead">%s</p>' % esc(t['intro']),
            '<h2>How to use it</h2><ol class="howto">' + ''.join('<li><b>%s</b>%s</li>' % (esc(s[0]), (' ' + esc(s[1])) if s[1] else '') for s in steps) + '</ol>',
            '<h2>Questions</h2><dl class="faq-list">' + ''.join('<dt>%s</dt><dd>%s</dd>' % (esc(q), esc(a)) for q, a in t['faq']) + '</dl>',
            '<h2>Related tools</h2><div class="rel">%s</div>' % related_links(t.get('related', [])),
            '<p class="seo-more"><a href="/tools/">All tools</a> &middot; <a href="/formats/">All %d conversions</a></p>' % len(SEO_PAIRS),
            '</section>']
    page = replace_block(BASE, 'page:meta', page_meta(t['title'], t['desc'], path, extra_meta=extra, jsonld=[crumb_ld, howto_ld, faq_ld, app_ld]))
    page = replace_block(page, 'page:body', '\n'.join(body))
    page = page.replace('<h1>Free Online File Converter</h1>', '<h1>%s</h1>' % esc(t['h1']))
    page = page.replace(HERO_P, '<p>%s</p>' % esc(t['desc']))
    page = page.replace('<div class="section">', '<div class="section" hidden>', 1)          # the format chooser is the converter's, not ours
    page = page.replace('</body>', TOOL_JS + '\n</body>')
    write(path + 'index.html', strip_home(page))

# ---- /tools/ hub
th = ['<section class="seo hub tools-hub">']
th_crumb, th_crumb_ld = crumbs([('Home', '/'), ('Tools', None)])
th.append(th_crumb)
th.append('<p class="lead">All the file tools you need in one place. From compression to conversion, image editing to PDF '
          'management \u2014 everything runs in your browser, and nothing is uploaded.</p>')
_tags = {TOOLPAGES.RAIL_ORDER[0]: 'Most used', TOOLPAGES.RAIL_ORDER[1]: 'Most used', TOOLPAGES.RAIL_ORDER[2]: 'Popular'}
for gid, gname in TOOLPAGES.GROUPS:
    members = [x for x in TOOLPAGES.TOOLS if x['group'] == gid]
    th.append('<h2>%s</h2><div class="tgrid">' % gname)
    for x in members:
        _hint, _icon = TOOLPAGES.RAIL_META[x['slug']]
        th.append('<a class="tcard" href="/%s/"><span class="ic" style="--fam:var(--f-%s)"><svg><use href="#t-%s"/></svg></span>'
                  '<h3>%s</h3><p>%s</p>%s</a>'
                  % (x['slug'], TOOLPAGES.GROUP_FAM[gid], _icon, esc(x['name']), esc(_hint),
                     ('<span class="ttag">%s</span>' % _tags[x['slug']]) if x['slug'] in _tags else ''))
    th.append('</div>')
th.append('<div class="tools-foot"><p>%d tools available &bull; No signup required &bull; No file limits</p><a class="btn primary" href="/">Start converting <span>&rarr;</span></a></div>' % len(TOOLPAGES.TOOLS))
th.append('<h2>Fixed sizes</h2><div class="rel">%s</div>' % ''.join(
    '<a href="/%s/">%s</a>' % (p['slug'], esc(p['h1'])) for p in TOOLPAGES.all_pages() if p.get('parent')))
th.append('</section>')
th_page = replace_block(BASE, 'page:meta', page_meta(
    'Free Online Tools \u2014 Compress, PDF, OCR, QR, Nothing Uploaded',
    'Free browser tools: compress an image or PDF to a size, passport photo, merge and split PDF, OCR, trim video, cut MP3, QR codes, unzip. Nothing uploaded.',
    'tools/', jsonld=[th_crumb_ld]))
th_page = replace_block(th_page, 'page:body', '\n'.join(th))
th_page = th_page.replace('<h1>Free Online File Converter</h1>', '<h1>Tools</h1>')
th_page = th_page.replace(HERO_P, '<p>%d tools that work on your device. Pick one below.</p>' % len(TOOLPAGES.TOOLS))
write('tools/index.html', hide_converter(strip_home(th_page)))

# ---- /embed/: the converter alone, for other sites to put in an iframe
emb = BASE
emb = re.sub(r'(?s)<header class="nav">.*?</header>', '', emb, count=1)
emb = re.sub(r'(?s)<footer class="footer">.*?</footer>', '', emb, count=1)
emb = emb.replace('<body>', '<body class="embed">', 1)
emb = replace_block(emb, 'page:meta', page_meta('Convert Files widget', 'Embedded file converter.', 'embed/',
                                              extra_meta='<meta name="robots" content="noindex,nofollow">'))
emb = replace_block(emb, 'page:body', '<p class="powered">Powered by <a href="%s/?ref=widget" target="_blank" rel="noopener">Convert Files</a> — free file converter, nothing uploaded</p>' % DOMAIN)
emb = emb.replace(HERO_P, '<p>Pick a file, choose what it should become, download the result. Nothing is uploaded.</p>')
os.makedirs('embed', exist_ok=True)
open('embed/index.html', 'w').write(strip_home(emb))      # noindex: kept out of the sitemap on purpose

# ---- /widget/: how to embed it
snippet = ('<iframe src="%s/embed/" title="Convert Files — free file converter" width="100%%" height="620" '
           'style="border:0;border-radius:12px" loading="lazy" allow="clipboard-write"></iframe>') % DOMAIN
wd = ['<section class="seo">']
wd_crumb, wd_crumb_ld = crumbs([('Home', '/'), ('Widget', None)])
wd.append(wd_crumb)
wd.append('<p class="lead">Put a working file converter on your own website with one line of HTML. It is free, carries no ads of ours, '
          'and your visitors’ files never leave their browser — they are not sent to you, and not to us.</p>')
wd.append('<h2>The code</h2><p>Paste this where you want the converter to appear:</p><pre class="snippet">%s</pre>' % esc(snippet))
wd.append('<h2>What it looks like</h2><div class="widget-demo">%s</div>' % snippet)
wd.append('<h2>Questions</h2><dl class="faq-list">'
          '<dt>Does it cost anything?</dt><dd>No. Use it on any site, commercial or not.</dd>'
          '<dt>Do my visitors’ files go through your server?</dt><dd>No. The widget is the same browser-side converter as the site: files are read, converted and downloaded on the visitor’s own device.</dd>'
          '<dt>Can I change the look?</dt><dd>The width and height are yours to set. The colours follow the visitor’s light or dark setting.</dd>'
          '<dt>What do you get out of it?</dt><dd>A small “Powered by Convert Files” line under the converter, linking here. Please keep it.</dd>'
          '</dl>')
wd.append('</section>')
wd_page = replace_block(BASE, 'page:meta', page_meta('Free File Converter Widget for Your Site — One Line of HTML',
                                                    'Embed a free, private file converter on your website with one iframe. Files never leave the visitor’s browser. No cost, no sign-up.',
                                                    'widget/', jsonld=[wd_crumb_ld]))
wd_page = replace_block(wd_page, 'page:body', '\n'.join(wd))
wd_page = wd_page.replace('<h1>Free Online File Converter</h1>', '<h1>Put a file converter on your website</h1>')
wd_page = wd_page.replace(HERO_P, '<p>One line of HTML. Free. Your visitors’ files stay in their browser.</p>')
write('widget/index.html', hide_converter(strip_home(wd_page)))

# ---- PWA: manifest and service worker (the shell is precached with this build's version)
manifest = {
    'name': 'Convert Files', 'short_name': 'Convert Files', 'id': '/', 'start_url': '/?source=pwa', 'scope': '/',
    'display': 'standalone', 'background_color': '#0e141c', 'theme_color': '#0E7C86',
    'description': 'Free file converter that runs entirely on your device. Nothing is uploaded.',
    'icons': [{'src': '/assets/icon-192.png', 'sizes': '192x192', 'type': 'image/png', 'purpose': 'any'},
              {'src': '/assets/icon-512.png', 'sizes': '512x512', 'type': 'image/png', 'purpose': 'any maskable'}],
    'share_target': {'action': '/share/', 'method': 'POST', 'enctype': 'multipart/form-data',
                     'params': {'files': [{'name': 'files', 'accept': ['image/*', 'video/*', 'audio/*', 'application/pdf', 'application/zip',
                                                                       '.docx', '.xlsx', '.pptx', '.csv', '.txt', '.md', '.json', '.xml', '.epub', '.heic', '.stl', '.obj', '.glb']}]}},
    'shortcuts': [{'name': 'Compress image', 'url': '/compress-image/?source=pwa'}, {'name': 'Merge PDF', 'url': '/merge-pdf/?source=pwa'},
                  {'name': 'HEIC to JPG', 'url': '/heic-to-jpg/?source=pwa'}]
}
open('manifest.webmanifest', 'w').write(json.dumps(manifest, indent=1) + '\n')
sw = open('pages/sw.js').read()
shell = ['/', '/css/app.css?v=%s' % VER] + ['/js/%s?v=%s' % (f, VER) for f in sorted(os.listdir('js')) if f.endswith('.js')] + \
        ['/assets/fonts/manrope-latin.woff2', '/assets/fonts/sora-latin.woff2', '/assets/fonts/jetbrains-mono-latin.woff2', '/assets/favicon.svg', '/manifest.webmanifest']
open('sw.js', 'w').write(sw.replace('{{VER}}', VER).replace('{{SHELL}}', json.dumps(shell)))


# ------------------------------------------------------------- IndexNow key
# Bing, Yandex, DuckDuckGo and Yahoo accept URL submissions signed by a key the
# site hosts at /<key>.txt. seo/indexnow.py does the submitting.
_ink = SITE.get('indexnow_key', '').strip()
if _ink:
    open(_ink + '.txt', 'w').write(_ink)   # not write(): it is not a page for the sitemap

# -------------------------------------------------------------- legal pages
shell = open('pages/_shell.html').read()
for name in ['privacy', 'terms', 'contact']:
    raw = open('pages/%s.html' % name).read()
    title = re.search(r'<!-- title: (.*?) -->', raw).group(1)
    desc = re.search(r'<!-- description: (.*?) -->', raw).group(1)
    content = re.sub(r'<!-- (title|description): .*? -->\n', '', raw)
    ga = SITE.get('ga4_measurement_id', '').strip()
    content = re.sub(r'\{\{#ga\}\}(.*?)\{\{/ga\}\}', (r'\1' if ga else ''), content, flags=re.S)
    page = shell
    for k, v in {'title': title, 'description': desc, 'path': name + '.html', 'domain': DOMAIN, 'v': VER, 'robots': '',
                 'head': site_head(), 'content': content}.items():
        page = page.replace('{{%s}}' % k, v)
    for k, v in {'email': SITE.get('contact_email', ''), 'date': TODAY, 'host': HOST}.items():
        page = page.replace('{{%s}}' % k, v)
    write(name + '.html', page)

nf = shell
for k, v in {'title': 'Page not found', 'description': 'That link does not go anywhere. Head back to Convert Files to convert images, PDF, Word, Excel, audio, video and 3D models for free.', 'path': '404.html', 'domain': DOMAIN, 'v': VER, 'head': site_head(),
             'robots': '\n<meta name="robots" content="noindex,follow">',
             'content': '<h1>Page not found</h1><p class="upd">That link does not go anywhere.</p><p><a class="btn primary" href="/">Back to the converter</a></p>'}.items():
    nf = nf.replace('{{%s}}' % k, v)
write('404.html', nf)


# --------------------------------------------------------------- admin
adm = open('admin/index.html').read()
adm = re.sub(r'\?v=[0-9a-f]+', '?v=' + VER, adm)
adm = replace_block(adm, 'site:head', site_head())
open('admin/index.html', 'w').write(adm)

# --------------------------------------------------- sitemap, robots, ads, CNAME
today = datetime.date.today().isoformat()
urls = [DOMAIN + '/'] + [DOMAIN + '/' + p.replace('index.html', '') for p in GENERATED if p != 'index.html' and p != '404.html']
sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for u in urls:
    sitemap.append('  <url><loc>%s</loc><lastmod>%s</lastmod></url>' % (esc(u), today))
sitemap.append('</urlset>')
write('sitemap.xml', '\n'.join(sitemap) + '\n')
write('robots.txt', 'User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n' % DOMAIN)
client = SITE.get('adsense_client', '').strip()
write('ads.txt', ('google.com, %s, DIRECT, f08c47fec0942fa0\n' % client.replace('ca-', '')) if client else '# Add your AdSense line here after approval, e.g.\n# google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0\n')
write('CNAME', HOST + '\n')
write('.nojekyll', '')

print('built %d files for %s (assets v=%s, adsense %s, analytics %s)' % (
    len(GENERATED), DOMAIN, VER, 'on' if client else 'off — set adsense_client in site.json', 'on' if SITE.get('ga4_measurement_id') else 'off'))
