/* sw.js — GENERATED by build.py from pages/sw.js. Offline shell, cached libraries, share target.
   Nothing here talks to a server on our behalf: the worker only caches what the page itself fetches. */
var VER = '1e5bbd7b';
var SHELL_CACHE = 'cf-shell-' + VER, LIB_CACHE = 'cf-libs-v1', PAGE_CACHE = 'cf-pages-v1';
var SHELL = ["/", "/css/app.css?v=1e5bbd7b", "/js/app.js?v=1e5bbd7b", "/js/content.js?v=1e5bbd7b", "/js/convert.js?v=1e5bbd7b", "/js/db.js?v=1e5bbd7b", "/js/docmodel.js?v=1e5bbd7b", "/js/encoders.js?v=1e5bbd7b", "/js/formats.js?v=1e5bbd7b", "/js/imaging.js?v=1e5bbd7b", "/js/tools.js?v=1e5bbd7b", "/assets/fonts/manrope-latin.woff2", "/assets/fonts/sora-latin.woff2", "/assets/fonts/jetbrains-mono-latin.woff2", "/assets/favicon.svg", "/manifest.webmanifest"];
var LIB_HOSTS = ['cdn.jsdelivr.net', 'cdnjs.cloudflare.com', 'unpkg.com', 'tessdata.projectnaptha.com'];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(SHELL_CACHE).then(function (c) { return c.addAll(SHELL); }).then(function () { return self.skipWaiting(); }));
});
self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf('cf-shell-') === 0 && k !== SHELL_CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

// Files shared into the app from the OS share sheet arrive here as a POST.
// They are parked in IndexedDB for the page to pick up, then the page opens.
function openShareDb() {
  return new Promise(function (res, rej) {
    var r = indexedDB.open('cf-share', 1);
    r.onupgradeneeded = function () { r.result.createObjectStore('files', { autoIncrement: true }); };
    r.onsuccess = function () { res(r.result); };
    r.onerror = function () { rej(r.error); };
  });
}
function parkShared(files) {
  return openShareDb().then(function (db) {
    return new Promise(function (res, rej) {
      var tx = db.transaction('files', 'readwrite'), st = tx.objectStore('files');
      st.clear();
      files.forEach(function (f) { st.add(f); });
      tx.oncomplete = function () { res(); };
      tx.onerror = function () { rej(tx.error); };
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request, url = new URL(req.url);
  if (req.method === 'POST' && url.origin === location.origin && url.pathname === '/share/') {
    e.respondWith(req.formData().then(function (fd) {
      var files = fd.getAll('files').filter(function (f) { return f && f.size !== undefined; });
      return parkShared(files).then(function () { return Response.redirect('/?shared=1', 303); });
    }).catch(function () { return Response.redirect('/', 303); }));
    return;
  }
  if (req.method !== 'GET') return;

  // pages: network first, fall back to what we have, then to the home page
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(function (r) {
      var copy = r.clone(); caches.open(PAGE_CACHE).then(function (c) { c.put(req, copy); });
      return r;
    }).catch(function () {
      return caches.match(req).then(function (m) { return m || caches.match('/'); });
    }));
    return;
  }
  // our own versioned assets: cache first
  if (url.origin === location.origin && /^\/(js|css|assets)\//.test(url.pathname) || url.pathname === '/manifest.webmanifest') {
    e.respondWith(caches.match(req).then(function (m) {
      return m || fetch(req).then(function (r) { var copy = r.clone(); caches.open(SHELL_CACHE).then(function (c) { c.put(req, copy); }); return r; });
    }));
    return;
  }
  // converter libraries from CDNs: cache first, so a format you used once works offline
  if (LIB_HOSTS.indexOf(url.hostname) >= 0) {
    e.respondWith(caches.match(req).then(function (m) {
      return m || fetch(req).then(function (r) { if (r.ok || r.type === 'opaque') { var copy = r.clone(); caches.open(LIB_CACHE).then(function (c) { c.put(req, copy); }); } return r; });
    }));
  }
  // everything else (the analytics API) goes straight to the network
});
